---
title: "Final Project"
---

## Overview

The [final project](https://classroom.github.com/a/y5OH1_Up) is an opportunity to bring all of the things you've learned in the course into a single reproducible workflow to answer a question of your choosing. Because each of you are in different stages of collecting your own data and because confronting datasets that aren’t yours can help clarify important concepts and design elements, I’m asking you to **develop an analysis of data that isn’t yours**. This final project should help you demonstrate:

* Proper data management, cleaning, and manipulation technques

* The ability to summarize spatial data and apply different statistical analyses to it

* The ability to evaluate the performance of statistical models

* The ability to generate visualizations that support your analyses

* The ability to integrate code, analysis, and visualization with text descrbing your approach and discussing your results

## Requirements

**Datasets.** The ability to manipulate and integrate a variety of data types, resolutions, and formats is a key component of this course. Your analysis should incorporate at least 5 datasets. The ultimate compostion of your database is up to you, but I'd like you to include 1 tabular dataset, 1 vector dataset, and 1 raster dataset. You should choose the other 2 (or more) to give you practice with the data types that are most relevant to your objectives and/or research.

**Analyses.** You've learned several classes of analyses (e.g., overlays, point-pattern, multivariate regression, and statistical learning). Apply at least one (preferably the one most tied to your own objectives and research) of these analyses to address your question. In the course of doing so, you'll need to justify your choice, assess whether your data meets appropriate assumptions, and evaluate the implications of key assumptions you make. For example, if you're conducting an overlay analysis, how does your choice of threshold affect the ultimate result? If you've fit a statistical model based on summary statistics (e.g, mean, median), how well does the model fit? How does the model change if you use different slices of the data?

**Visualizations.** You should produce a minimum of 3 visualizations to accompany your analysis. One of these should be a publication quality location map. The others are up to you, but should a) help you tell the story of your analysis and b) help you meet your objectives for the course and your own research. These can be additional maps of results, figures that summarize your data or results in non-spatial ways, or interactive graphics that allow you to explore parts of your analysis. 

**Reporting**
You can generate a 'manuscript' style document (using Quarto) or a flexdashboard (using Quarto and shiny) as the final product. Your report should include:

1. A brief (1-2 paragraphs) description of your question and why you're interested in it.

2. A Methods section with subsections describing the data sources, any processing steps you took and why, and your process for the analysis. Show your code and provide annotation to describe what you are attempting do with the various steps.

3. A Results section that includes tabular results as well as any relevant visualizations that describe your data and analysis.

4. A Discussion of your results that puts your results in the context of your question, considers alternative analysis strategies and why they may or may not be better than the approach you chose, describes additional data that might be important for your question, and considers the role of extent and resolution in your analysis.

## Assessment

This is the final project, but there are several steps along the way! First, you'll need to submit objectives (`docs/grading_contract.qmd`) which form the basis for assessment of the project. This is due **October 1**. Then, you'll need to submit a brief description of your project (`docs/project_description.qmd`) on **November 1**. 

::: {.callout-important}
You'll submit each of these documents by making commits prior to the deadline. After the deadline passes I'll add my comments to the documents.
:::

You'll submit a draft of the final report (`docs/main_project_doc.qmd`) on **December 9**. I'll give you feedback based on your project and on your objectives for the course. You'll then have a chance to address my feedback before turning in your final draft on **December 18**. Your final self-assessment will ask you to reflect on your objectives for the course and evaluate the degree to which your final project demonstrates that you achieved your objectives. *Thus, when you are designing your project, make sure that you have your initial objectives in mind.*


We'll use a form of [contract grading](https://en.wikipedia.org/wiki/Contract_grading#:~:text=Contract%20grading%20is%20a%20form,correspond%20to%20specific%20letter%20grades.) to determine your grades on the final. Contract grading allows us to have a conversation about what you want out of the course, what you expect to put into it, and what I think you need to be successful in deploying the skills we learn here. Based on your goals for course, we'll sign a contract that instantiates your objectives into the grade you'll receive for the final. Complete the final and meet your objectives and you'll get the grade you chose. 

Scoring for the final project will be based on the percentage of the objectives you achieve (i.e., meet 9 out of 10 of your objectives means you get 90% of the points)



:::{.callout-note}
**A note on grades**: You will be responsible for assessing how well your assignment demonstrates that you achieved your objectives. I reserve the right to change the grade you've given yourself, but will provide clear justification for why I'm doing that. _Without a completed self-assessment there is no grade for your final project_, so please make sure you complete it.
:::