{
  "hash": "7f452838ad4fb06325ef12cf592d71e6",
  "result": {
    "markdown": "---\ntitle: \"Data Models, Coordinates, and Geometries\"\n---\n\n\n## Objectives\n\nWe're going to introduce the `sf`, `terra`, and `tidyterra` packages today as a way of reading and inspecting spatial data. By the end of this lesson, you should be able to:\n\n1. Read in spatial data from both the vector and raster data model.\n\n2. Recognize the required components of a spatial data object\n\n3. Use `plot` as a way to perform a quick check on your data.\n\n\n\n## Getting Started\n\nFirst, [join the repository](https://classroom.github.com/a/XWzfBM16). Then, we'll have to [get our credentials](https://rstudio.aws.boisestate.edu/) and login to a [new RStudio session](https://rstudio.apps.aws.boisestate.edu/). Finally, create a new, version control, git-based project (using the link to the repo you just created). \n\nOnce you've done that, you'll need to load your packages. We're going to add 3 new packages to the `tidyverse`; the `sf`, `terra`, and `tidyterra` packages. We'll also add the `googledrive` so that we can use a custom function for downloading data from a shared Google Drive folder. Note that when you load these, the conflicts that the `tidyverse` reports will be different. In order to overcome these conflicts, you'll need to use explicit calls like `package::function` so `R` knows which ones to use.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(googledrive)\nlibrary(sf)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'sf' was built under R version 4.4.1\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLinking to GEOS 3.11.0, GDAL 3.5.3, PROJ 9.1.0; sf_use_s2() is TRUE\n```\n:::\n\n```{.r .cell-code}\nlibrary(terra)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nterra 1.7.78\n```\n:::\n\n```{.r .cell-code}\nlibrary(tidyterra)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'tidyterra'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:stats':\n\n    filter\n```\n:::\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'ggplot2' was built under R version 4.4.1\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   3.5.2     ✔ tibble    3.2.1\n✔ lubridate 1.9.3     ✔ tidyr     1.3.1\n✔ purrr     1.0.2     \n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ tidyr::extract() masks terra::extract()\n✖ dplyr::filter()  masks tidyterra::filter(), stats::filter()\n✖ dplyr::lag()     masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n:::\n:::\n\n\n## Loading a Custom Function\n\nYou'll notice that your `scripts/utilities` folder has a file called `download_utils.R`. This file has some custom functions for downloading data directly from websites and from a Google Drive Folder. In order to give yourself access to these functions you'll need to `source` them into your environment. You can do this by typing:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsource(\"scripts/utilities/download_utils.R\")\n```\n:::\n\n\nThe first time you run the `gdrive_folder_download` function, you'll be taken to a webpage where you need to give `googledrive` access to your Google Drive folders. Make sure you've checked all the boxes and click Allow. You should get a message saying that authorization is complete and that you can close the tab.\n\nLet's run it now and download the data to our `original` folder. You'll see that it requires two arguments, `filelst` and `dstfldr`. The first is a list of files in the folder, the second is the name of the destination folder. In order to generate the `filelst` we need to do some `googledrive` gymnastics to generate a data frame of the unique google drive id's for each file. We then use `pmap` to download each file. You'll notice that the destination path is printed to the screen.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfile_list <- drive_ls(drive_get(as_id(\"https://drive.google.com/drive/u/1/folders/1PwfUX2hnJlbnqBe3qvl33tFBImtNFTuR\")))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n! Using an auto-discovered, cached token.\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n  To suppress this message, modify your code or options to clearly consent to\n  the use of a cached token.\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n  See gargle's \"Non-interactive auth\" vignette for more details:\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n  <https://gargle.r-lib.org/articles/non-interactive-auth.html>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nℹ The googledrive package is using a cached token for\n  'mattwilliamson@boisestate.edu'.\n```\n:::\n\n```{.r .cell-code}\nfile_list %>% \n  dplyr::select(id, name) %>%\n  purrr::pmap(function(id, name) {\n    gdrive_folder_download(list(id = id, name = name),\n                           dstfldr = \"inclass07\")\n  })\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nFile downloaded:\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n• 'pa_censors_loc.csv' <id: 13ZPu8E96ERWdUNlwQ5MB_vXrPCqvzxj_>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nSaved locally as:\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n• 'data/original/inclass07/pa.csv'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nFile downloaded:\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n• 'wildfire_hazard_agg.tif' <id: 135PvMlKu17i7tZcrF7XiWxzrzaX-aCLn>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nSaved locally as:\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n• 'data/original/inclass07/wildfire.tif'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nFile downloaded:\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n• 'cejst_nw.shx' <id: 1IXDayQ35MwCfq1UtuDHCtf5iNYq5VUqu>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nSaved locally as:\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n• 'data/original/inclass07/cejst.shx'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nFile downloaded:\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n• 'cejst_nw.dbf' <id: 1PgCOsZsVEOhxQs2Dpz21MNz0kMb32amB>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nSaved locally as:\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n• 'data/original/inclass07/cejst.dbf'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nFile downloaded:\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n• 'cejst_nw.shp' <id: 1ZeL_683mTTWdCDjQ4dY6oJsxyVZtQT6O>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nSaved locally as:\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n• 'data/original/inclass07/cejst.shp'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nFile downloaded:\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n• 'cejst_nw.prj' <id: 1r7OHK1DHhoEMBToiM2FmuK5xmEzWSdrc>\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nSaved locally as:\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n• 'data/original/inclass07/cejst.prj'\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[[1]]\n[1] \"data/original/inclass07/pa.csv\"\n\n[[2]]\n[1] \"data/original/inclass07/wildfire.tif\"\n\n[[3]]\n[1] \"data/original/inclass07/cejst.shx\"\n\n[[4]]\n[1] \"data/original/inclass07/cejst.dbf\"\n\n[[5]]\n[1] \"data/original/inclass07/cejst.shp\"\n\n[[6]]\n[1] \"data/original/inclass07/cejst.prj\"\n```\n:::\n:::\n\n\n## Reading Data: Vectors\n\nThe vector data (called `cejst`) comes from the Climate and Environmental Justice Screening Tool which is no longer available online. You'll notice that there are multiple files with the same name, but different extensions. We'll talk more about these different files in the next few weeks, but for now, just not that these files exist. \n\nBecause `sf` adheres to the `tidyverse` grammars, we can use a similar intuition to read in the data. You'll note that even though we have all these extra files, we only need the `.shp` file. This is the shapefile which is the \"overarching\" file for all of the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncejst_shp <- read_sf(\"data/original/inclass07/cejst.shp\")\n```\n:::\n\n\nNow that you've got the data in, let's take a look at it using `str` and  `glimpse`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(cejst_shp)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nsf [2,590 × 124] (S3: sf/tbl_df/tbl/data.frame)\n $ GEOID10   : chr [1:2590] \"16019970700\" \"16025970100\" \"16027021700\" \"16027020700\" ...\n $ SF        : chr [1:2590] \"Idaho\" \"Idaho\" \"Idaho\" \"Idaho\" ...\n $ CF        : chr [1:2590] \"Bonneville County\" \"Camas County\" \"Canyon County\" \"Canyon County\" ...\n $ DF_PFS    : num [1:2590] 0.44 0.67 0.74 0.48 0.75 0.8 0.76 0.72 0.76 0.52 ...\n $ AF_PFS    : num [1:2590] 0.73 0.65 0.86 0.63 0.79 0.88 0.86 0.79 0.8 0.65 ...\n $ HDF_PFS   : num [1:2590] 0.57 0.79 0.69 0.47 0.72 0.55 0.53 0.71 0.74 0.45 ...\n $ DSF_PFS   : num [1:2590] 0.53 0 0.58 0.46 0.12 0.79 0.68 0.27 0.06 0.11 ...\n $ EBF_PFS   : num [1:2590] 0.63 0.95 0.54 0.3 0.63 0.81 0.81 0.44 0.73 0.52 ...\n $ EALR_PFS  : num [1:2590] 0.55 0.83 0.63 0.63 0.65 NA 0.41 0.64 0.65 0.64 ...\n $ EBLR_PFS  : num [1:2590] 0.19 0.93 0.05 0.55 0.09 0.09 0.08 0.09 0.47 0.17 ...\n $ EPLR_PFS  : num [1:2590] 0.8 0.99 0.09 0.1 0.11 0.31 0.08 0.09 0.1 0.09 ...\n $ HBF_PFS   : num [1:2590] 0.69 0.6 0.53 0.07 0.46 0.86 0.93 0.22 0.53 0.28 ...\n $ LLEF_PFS  : num [1:2590] 0.73 0.48 0.67 0.29 0.51 0.87 0.62 0.38 0.32 0.26 ...\n $ LIF_PFS   : num [1:2590] 0.54 0.54 0.53 0.12 0.48 0.61 0.88 0.46 0.41 0.32 ...\n $ LMI_PFS   : num [1:2590] 0.81 0.75 0.61 0.25 0.55 0.92 0.95 0.44 0.42 0.35 ...\n $ PM25F_PFS : num [1:2590] 0.11 0 0.68 0.63 0.42 0.66 0.69 0.57 0.26 0.4 ...\n $ HSEF      : num [1:2590] 0.14 0.06 0.2 0.08 0.21 0.24 0.31 0.18 0.18 0.09 ...\n $ P100_PFS  : num [1:2590] 0.83 0.63 0.47 0.24 0.6 0.72 0.93 0.27 0.39 0.33 ...\n $ P200_I_PFS: num [1:2590] 0.86 0.71 0.81 0.39 0.75 0.98 0.91 0.49 0.67 0.54 ...\n $ AJDLI_ET  : int [1:2590] 1 1 1 0 1 1 1 0 1 1 ...\n $ LPF_PFS   : num [1:2590] 0.75 0.52 0.26 0.3 0.65 0.62 0.63 0.4 0.51 0.36 ...\n $ KP_PFS    : num [1:2590] 0.86 0.21 0.84 0.21 0.61 0.57 0.21 0.43 0.9 0.21 ...\n $ NPL_PFS   : num [1:2590] 0.09 0.05 0.06 0.08 0.03 0.08 0.05 0.05 0.08 0.1 ...\n $ RMP_PFS   : num [1:2590] 0.49 0.01 0.56 0.84 0.26 0.96 0.58 0.36 0.1 0.2 ...\n $ TSDF_PFS  : num [1:2590] 0.22 0.01 0.14 0.42 0.07 0.55 0.13 0.11 0.1 0.19 ...\n $ TPF       : num [1:2590] 5589 1048 11701 3901 5059 ...\n $ TF_PFS    : num [1:2590] 0.55 0.06 0.54 0.53 0.28 0.71 0.83 0.24 0.05 0.09 ...\n $ UF_PFS    : num [1:2590] 0.61 0.16 0.64 0.33 0.66 0.86 0.8 0.45 0.47 0.61 ...\n $ WF_PFS    : num [1:2590] 0.03 0.11 0.98 0.24 0.79 0.98 0.98 0.85 0.42 0.04 ...\n $ UST_PFS   : num [1:2590] 0.59 0.02 0.44 0.31 0.17 0.73 0.83 0.13 0.06 0.18 ...\n $ N_WTR     : int [1:2590] 0 0 1 0 0 1 1 0 0 0 ...\n $ N_WKFC    : int [1:2590] 0 0 0 0 0 1 1 0 0 0 ...\n $ N_CLT     : int [1:2590] 0 1 0 0 0 1 1 0 0 0 ...\n $ N_ENY     : int [1:2590] 0 1 0 0 0 0 0 0 0 0 ...\n $ N_TRN     : int [1:2590] 0 0 0 0 0 0 0 0 1 0 ...\n $ N_HSG     : int [1:2590] 0 0 0 0 0 0 1 0 1 0 ...\n $ N_PLN     : int [1:2590] 0 0 0 0 0 1 0 0 0 0 ...\n $ N_HLTH    : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...\n $ SN_C      : int [1:2590] 0 1 1 0 0 1 1 0 1 0 ...\n $ SN_T      : chr [1:2590] NA NA NA NA ...\n $ DLI       : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...\n $ ALI       : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...\n $ PLHSE     : int [1:2590] 0 0 0 0 0 0 1 0 0 0 ...\n $ LMILHSE   : int [1:2590] 0 0 0 0 0 1 1 0 0 0 ...\n $ ULHSE     : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...\n $ EPL_ET    : int [1:2590] 0 1 0 0 0 0 0 0 0 0 ...\n $ EAL_ET    : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...\n $ EBL_ET    : int [1:2590] 0 1 0 0 0 0 0 0 0 0 ...\n $ EB_ET     : int [1:2590] 0 1 0 0 0 0 0 0 0 0 ...\n $ PM25_ET   : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...\n $ DS_ET     : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...\n $ TP_ET     : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...\n $ LPP_ET    : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...\n $ HRS_ET    : chr [1:2590] NA NA NA NA ...\n $ KP_ET     : int [1:2590] 0 0 0 0 0 0 0 0 1 0 ...\n $ HB_ET     : int [1:2590] 0 0 0 0 0 0 1 0 0 0 ...\n $ RMP_ET    : int [1:2590] 0 0 0 0 0 1 0 0 0 0 ...\n $ NPL_ET    : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...\n $ TSDF_ET   : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...\n $ WD_ET     : int [1:2590] 0 0 1 0 0 1 1 0 0 0 ...\n $ UST_ET    : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...\n $ DB_ET     : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...\n $ A_ET      : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...\n $ HD_ET     : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...\n $ LLE_ET    : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...\n $ UN_ET     : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...\n $ LISO_ET   : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...\n $ POV_ET    : int [1:2590] 0 0 0 0 0 0 1 0 0 0 ...\n $ LMI_ET    : int [1:2590] 0 0 0 0 0 1 1 0 0 0 ...\n $ IA_LMI_ET : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...\n $ IA_UN_ET  : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...\n $ IA_POV_ET : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...\n $ TC        : num [1:2590] 0 3 1 0 0 4 5 0 2 0 ...\n $ CC        : num [1:2590] 0 2 1 0 0 4 4 0 2 0 ...\n $ IAULHSE   : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...\n $ IAPLHSE   : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...\n $ IALMILHSE : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...\n $ IALMIL_76 : num [1:2590] NA NA NA NA NA NA NA NA NA NA ...\n $ IAPLHS_77 : num [1:2590] NA NA NA NA NA NA NA NA NA NA ...\n $ IAULHS_78 : num [1:2590] NA NA NA NA NA NA NA NA NA NA ...\n $ LHE       : int [1:2590] 1 0 1 0 1 1 1 1 1 0 ...\n $ IALHE     : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...\n $ IAHSEF    : num [1:2590] NA NA NA NA NA NA NA NA NA NA ...\n $ N_CLT_EOMI: int [1:2590] 0 1 0 0 0 1 1 0 0 0 ...\n $ N_ENY_EOMI: int [1:2590] 0 1 0 0 0 0 0 0 0 0 ...\n $ N_TRN_EOMI: int [1:2590] 0 0 0 0 0 0 0 1 1 0 ...\n $ N_HSG_EOMI: int [1:2590] 0 0 0 0 0 0 1 0 1 0 ...\n $ N_PLN_EOMI: int [1:2590] 0 0 0 0 0 1 0 0 0 0 ...\n $ N_WTR_EOMI: int [1:2590] 0 0 1 0 0 1 1 0 0 0 ...\n $ N_HLTH_88 : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...\n $ N_WKFC_89 : int [1:2590] 0 0 0 0 0 1 1 0 0 0 ...\n $ FPL200S   : int [1:2590] 1 1 1 0 1 1 1 0 1 0 ...\n $ N_WKFC_91 : int [1:2590] 1 0 1 0 1 1 1 1 1 0 ...\n $ TD_ET     : int [1:2590] 0 0 0 0 0 0 0 1 1 0 ...\n $ TD_PFS    : num [1:2590] 0.67 0.78 0.6 0.63 0.85 0.35 0.29 0.94 0.91 0.78 ...\n $ FLD_PFS   : num [1:2590] 0.83 0.88 0.43 0.24 0.82 0.93 0.97 0.44 0.49 0.71 ...\n $ WFR_PFS   : num [1:2590] 0.7 0.82 0.33 0.87 0.8 0.33 0.83 0.77 0.81 0.78 ...\n $ FLD_ET    : int [1:2590] 0 0 0 0 0 1 1 0 0 0 ...\n $ WFR_ET    : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...\n  [list output truncated]\n - attr(*, \"sf_column\")= chr \"geometry\"\n - attr(*, \"agr\")= Factor w/ 3 levels \"constant\",\"aggregate\",..: NA NA NA NA NA NA NA NA NA NA ...\n  ..- attr(*, \"names\")= chr [1:123] \"GEOID10\" \"SF\" \"CF\" \"DF_PFS\" ...\n```\n:::\n:::\n\n\nYou'll notice that this is a new data type:\n\n`sf [2,590 × 124] (S3: sf/tbl_df/tbl/data.frame)`\n\nYou can read this to yourself as \"cejst_shp\" is an `sf` object with a `tbl_df` combined with. it. (It's slightly more complicated than that, but this can give you an intuition). \n\nNow let's look at the output of glimpse:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(cejst_shp)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 2,590\nColumns: 124\n$ GEOID10    <chr> \"16019970700\", \"16025970100\", \"16027021700\", \"16027020700\",…\n$ SF         <chr> \"Idaho\", \"Idaho\", \"Idaho\", \"Idaho\", \"Idaho\", \"Idaho\", \"Idah…\n$ CF         <chr> \"Bonneville County\", \"Camas County\", \"Canyon County\", \"Cany…\n$ DF_PFS     <dbl> 0.44, 0.67, 0.74, 0.48, 0.75, 0.80, 0.76, 0.72, 0.76, 0.52,…\n$ AF_PFS     <dbl> 0.73, 0.65, 0.86, 0.63, 0.79, 0.88, 0.86, 0.79, 0.80, 0.65,…\n$ HDF_PFS    <dbl> 0.57, 0.79, 0.69, 0.47, 0.72, 0.55, 0.53, 0.71, 0.74, 0.45,…\n$ DSF_PFS    <dbl> 0.53, 0.00, 0.58, 0.46, 0.12, 0.79, 0.68, 0.27, 0.06, 0.11,…\n$ EBF_PFS    <dbl> 0.63, 0.95, 0.54, 0.30, 0.63, 0.81, 0.81, 0.44, 0.73, 0.52,…\n$ EALR_PFS   <dbl> 0.55, 0.83, 0.63, 0.63, 0.65, NA, 0.41, 0.64, 0.65, 0.64, 0…\n$ EBLR_PFS   <dbl> 0.19, 0.93, 0.05, 0.55, 0.09, 0.09, 0.08, 0.09, 0.47, 0.17,…\n$ EPLR_PFS   <dbl> 0.80, 0.99, 0.09, 0.10, 0.11, 0.31, 0.08, 0.09, 0.10, 0.09,…\n$ HBF_PFS    <dbl> 0.69, 0.60, 0.53, 0.07, 0.46, 0.86, 0.93, 0.22, 0.53, 0.28,…\n$ LLEF_PFS   <dbl> 0.73, 0.48, 0.67, 0.29, 0.51, 0.87, 0.62, 0.38, 0.32, 0.26,…\n$ LIF_PFS    <dbl> 0.54, 0.54, 0.53, 0.12, 0.48, 0.61, 0.88, 0.46, 0.41, 0.32,…\n$ LMI_PFS    <dbl> 0.81, 0.75, 0.61, 0.25, 0.55, 0.92, 0.95, 0.44, 0.42, 0.35,…\n$ PM25F_PFS  <dbl> 0.11, 0.00, 0.68, 0.63, 0.42, 0.66, 0.69, 0.57, 0.26, 0.40,…\n$ HSEF       <dbl> 0.14, 0.06, 0.20, 0.08, 0.21, 0.24, 0.31, 0.18, 0.18, 0.09,…\n$ P100_PFS   <dbl> 0.83, 0.63, 0.47, 0.24, 0.60, 0.72, 0.93, 0.27, 0.39, 0.33,…\n$ P200_I_PFS <dbl> 0.86, 0.71, 0.81, 0.39, 0.75, 0.98, 0.91, 0.49, 0.67, 0.54,…\n$ AJDLI_ET   <int> 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,…\n$ LPF_PFS    <dbl> 0.75, 0.52, 0.26, 0.30, 0.65, 0.62, 0.63, 0.40, 0.51, 0.36,…\n$ KP_PFS     <dbl> 0.86, 0.21, 0.84, 0.21, 0.61, 0.57, 0.21, 0.43, 0.90, 0.21,…\n$ NPL_PFS    <dbl> 0.09, 0.05, 0.06, 0.08, 0.03, 0.08, 0.05, 0.05, 0.08, 0.10,…\n$ RMP_PFS    <dbl> 0.49, 0.01, 0.56, 0.84, 0.26, 0.96, 0.58, 0.36, 0.10, 0.20,…\n$ TSDF_PFS   <dbl> 0.22, 0.01, 0.14, 0.42, 0.07, 0.55, 0.13, 0.11, 0.10, 0.19,…\n$ TPF        <dbl> 5589, 1048, 11701, 3901, 5059, 4681, 3006, 7423, 6653, 4693…\n$ TF_PFS     <dbl> 0.55, 0.06, 0.54, 0.53, 0.28, 0.71, 0.83, 0.24, 0.05, 0.09,…\n$ UF_PFS     <dbl> 0.61, 0.16, 0.64, 0.33, 0.66, 0.86, 0.80, 0.45, 0.47, 0.61,…\n$ WF_PFS     <dbl> 0.03, 0.11, 0.98, 0.24, 0.79, 0.98, 0.98, 0.85, 0.42, 0.04,…\n$ UST_PFS    <dbl> 0.59, 0.02, 0.44, 0.31, 0.17, 0.73, 0.83, 0.13, 0.06, 0.18,…\n$ N_WTR      <int> 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ N_WKFC     <int> 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ N_CLT      <int> 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ N_ENY      <int> 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ N_TRN      <int> 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,…\n$ N_HSG      <int> 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ N_PLN      <int> 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ N_HLTH     <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ SN_C       <int> 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,…\n$ SN_T       <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ DLI        <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ ALI        <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ PLHSE      <int> 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ LMILHSE    <int> 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ ULHSE      <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ EPL_ET     <int> 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ EAL_ET     <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ EBL_ET     <int> 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ EB_ET      <int> 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ PM25_ET    <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ DS_ET      <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ TP_ET      <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ LPP_ET     <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ HRS_ET     <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ KP_ET      <int> 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,…\n$ HB_ET      <int> 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ RMP_ET     <int> 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ NPL_ET     <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ TSDF_ET    <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ WD_ET      <int> 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ UST_ET     <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ DB_ET      <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ A_ET       <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ HD_ET      <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ LLE_ET     <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ UN_ET      <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ LISO_ET    <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ POV_ET     <int> 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ LMI_ET     <int> 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ IA_LMI_ET  <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ IA_UN_ET   <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ IA_POV_ET  <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ TC         <dbl> 0, 3, 1, 0, 0, 4, 5, 0, 2, 0, 0, 3, 0, 0, 0, 0, 1, 0, 0, 0,…\n$ CC         <dbl> 0, 2, 1, 0, 0, 4, 4, 0, 2, 0, 0, 3, 0, 0, 0, 0, 1, 0, 0, 0,…\n$ IAULHSE    <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ IAPLHSE    <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ IALMILHSE  <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ IALMIL_76  <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ IAPLHS_77  <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ IAULHS_78  <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ LHE        <int> 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ IALHE      <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ IAHSEF     <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ N_CLT_EOMI <int> 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ N_ENY_EOMI <int> 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ N_TRN_EOMI <int> 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,…\n$ N_HSG_EOMI <int> 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ N_PLN_EOMI <int> 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ N_WTR_EOMI <int> 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ N_HLTH_88  <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ N_WKFC_89  <int> 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ FPL200S    <int> 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,…\n$ N_WKFC_91  <int> 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ TD_ET      <int> 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,…\n$ TD_PFS     <dbl> 0.67, 0.78, 0.60, 0.63, 0.85, 0.35, 0.29, 0.94, 0.91, 0.78,…\n$ FLD_PFS    <dbl> 0.83, 0.88, 0.43, 0.24, 0.82, 0.93, 0.97, 0.44, 0.49, 0.71,…\n$ WFR_PFS    <dbl> 0.70, 0.82, 0.33, 0.87, 0.80, 0.33, 0.83, 0.77, 0.81, 0.78,…\n$ FLD_ET     <int> 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ WFR_ET     <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ ADJ_ET     <int> 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ IS_PFS     <dbl> 0.64, 0.16, 0.41, 0.53, 0.86, 0.46, 0.51, 0.70, 0.82, 0.86,…\n$ IS_ET      <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,…\n$ AML_ET     <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ FUDS_RAW   <chr> NA, NA, NA, NA, NA, NA, NA, NA, \"0\", NA, NA, NA, NA, NA, NA…\n$ FUDS_ET    <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ IMP_FLG    <chr> \"0\", \"0\", \"0\", \"0\", \"0\", \"0\", \"0\", \"0\", \"0\", \"0\", \"0\", \"0\",…\n$ DM_B       <dbl> 0.04, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.01,…\n$ DM_AI      <dbl> 0.01, 0.00, 0.01, 0.00, 0.00, 0.02, 0.01, 0.00, 0.00, 0.00,…\n$ DM_A       <dbl> 0.00, 0.00, 0.00, 0.01, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,…\n$ DM_HI      <dbl> 0.00, 0.00, 0.01, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,…\n$ DM_T       <dbl> 0.06, 0.00, 0.06, 0.04, 0.04, 0.06, 0.03, 0.01, 0.02, 0.00,…\n$ DM_W       <dbl> 0.62, 0.98, 0.59, 0.88, 0.71, 0.54, 0.40, 0.81, 0.83, 0.85,…\n$ DM_H       <dbl> 0.27, 0.01, 0.36, 0.07, 0.26, 0.42, 0.54, 0.16, 0.15, 0.11,…\n$ DM_O       <dbl> 0.11, 0.00, 0.15, 0.02, 0.11, 0.12, 0.27, 0.03, 0.02, 0.02,…\n$ AGE_10     <dbl> 0.18, 0.16, 0.15, 0.12, 0.12, 0.15, 0.17, 0.10, 0.10, 0.14,…\n$ AGE_MIDDLE <dbl> 0.71, 0.65, 0.71, 0.71, 0.68, 0.77, 0.72, 0.71, 0.76, 0.66,…\n$ AGE_OLD    <dbl> 0.10, 0.18, 0.13, 0.15, 0.18, 0.07, 0.09, 0.18, 0.12, 0.18,…\n$ TA_COU_116 <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ TA_COUNT_C <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ TA_PERC    <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ TA_PERC_FE <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ UI_EXP     <chr> \"Nation\", \"Nation\", \"Nation\", \"Nation\", \"Nation\", \"Nation\",…\n$ THRHLD     <dbl> 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21,…\n$ geometry   <MULTIPOLYGON [°]> MULTIPOLYGON (((-112.0208 4..., MULTIPOLYGON (…\n```\n:::\n:::\n\n\nThe key addition here is the `geometry` column. This is where the magic of `tibbles` comes in - it's a `list` column. These sorts of columns aren't allowed in `data.frames` because they entail multiple (and potentially different) data types. They become critical for spatial data (and `sf` objects) as they contain the coordinates for where the object need to go!\n\nIn the previous examples, you got used to checking the various columns for (in-)feasible values. You should still do this; however, the introduction of the `geometry` column. **Identifying problematic `geometry` is key component of ensuring your data is valid.** Luckly, you can do this with:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall(st_is_valid(cejst_shp))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] TRUE\n```\n:::\n:::\n\n\nThings look good for now! We'll talk more about what to do when this returns `FALSE` in future classes.\n\nOne final check is to take a look at the data. We'll learn more about how to make fancy maps in the future, but for now, there's a quick check:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(st_geometry(cejst_shp))\n```\n\n::: {.cell-output-display}\n![](07-lesson_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n\n## Reading Data: Rasters\n\nLet's switch gears a bit and run through same process with rasters. Unfortunately, the `terra` package uses a different syntax. I'll do my best to highlight those difference as we go, but for now, let's focus on the `terra` version of read.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_prob <- rast(\"data/original/inclass07/wildfire.tif\")\n```\n:::\n\n\nImportantly, `rast` does more than just read in data. You can look at `?rast` to learn some more of those functions.\n\nLet's look at the data with `str`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(fire_prob)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nS4 class 'SpatRaster' [package \"terra\"]\n```\n:::\n:::\n\n\nYou'll notice a much less verbose response that this is a `SpatRaster` data class. We'll talk more about what this means in the next few weeks, but for now, just notice that this is a distinct class assigned to a very particular package. \n\nWhat happens when you look at `glimpse`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(fire_prob)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#  A SpatRaster 4,016 x 4,607 x 1 layer (18,501,712 cells)\n#  Resolution (x / y): (240 / 240)\n#  Projected CRS: +proj=aea +lat_0=23 +lon_0=-96 +lat_1=29.5 +lat_2=45.5 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs\n#  CRS projection units: meter <m>\n#  Extent (x / y) : ([-2,294,745 / -1,189,065] , [ 2,208,735 /  3,172,575])\n\n$ WHP_ID <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n```\n:::\n:::\n\n\nYou get a variety of additional information on the resolution, projection, and extent. What you don't get, however, is a geometry or any info about where each cell should be. This is because for `raster` data, the geometry is **implicit** - if we know where the raster covers, and the cell size, then we know the rest of the information necessary to derie the geometry. The other thing you'll notice is that there's only 1 variable. This is again a function of the raster data type. Each layer can only contain information on one measurement and all of those measurements much be of the same data class. Rasters are essentially matrices where the rows are the x coordinates, the columns are the y coordinates, and the cell values are the measurement.\n\nThe last thing we might want to do is plot the raster to quickly make sure it looks like the thing we thought it would. The nice part about `terra` is that there is a basic `plot` function that you can use:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(fire_prob)\n```\n\n::: {.cell-output-display}\n![](07-lesson_files/figure-html/plotrst-1.png){width=672}\n:::\n:::",
    "supporting": [
      "07-lesson_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}