<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Intro to Spatial Data in R - Data Models, Coordinates, and Geometries</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="..//files/iSDR_logo.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<meta property="og:title" content="Intro to Spatial Data in R - Data Models, Coordinates, and Geometries">
<meta property="og:description" content="">
<meta property="og:image" content="https://isdrfall25.classes.spaseslab.com/files/social-image-f22.png">
<meta property="og:site-name" content="Intro to Spatial Data in R">
<meta property="og:locale" content="en_US">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Intro to Spatial Data in R</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../syllabus.html" rel="" target="">
 <span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../schedule.html" rel="" target="">
 <span class="menu-text">Schedule</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../content/index.html" rel="" target="">
 <span class="menu-text">Content</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../assignment/index.html" rel="" target="">
 <span class="menu-text">Assignments</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../example/index.html" rel="" target="">
 <span class="menu-text">Examples</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../lesson/index.html" rel="" target="">
 <span class="menu-text">Lessons</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../resource/index.html" rel="" target="">
 <span class="menu-text">Resources</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://ecostatsbsu.slack.com/archives/CV4DEJ8M7" rel="" target=""><i class="bi bi-slack" role="img" aria-label="Slack">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/BSU-Spatial-Data-in-R-Fall2025" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://rstudio.apps.aws.boisestate.edu/" rel="" target=""><i class="bi bi-cloud-fill" role="img" aria-label="Rstudio">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#objectives" id="toc-objectives" class="nav-link active" data-scroll-target="#objectives">Objectives</a></li>
  <li><a href="#getting-started" id="toc-getting-started" class="nav-link" data-scroll-target="#getting-started">Getting Started</a></li>
  <li><a href="#loading-a-custom-function" id="toc-loading-a-custom-function" class="nav-link" data-scroll-target="#loading-a-custom-function">Loading a Custom Function</a></li>
  <li><a href="#reading-data-vectors" id="toc-reading-data-vectors" class="nav-link" data-scroll-target="#reading-data-vectors">Reading Data: Vectors</a></li>
  <li><a href="#reading-data-rasters" id="toc-reading-data-rasters" class="nav-link" data-scroll-target="#reading-data-rasters">Reading Data: Rasters</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Data Models, Coordinates, and Geometries</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="objectives" class="level2">
<h2 class="anchored" data-anchor-id="objectives">Objectives</h2>
<p>We’re going to introduce the <code>sf</code>, <code>terra</code>, and <code>tidyterra</code> packages today as a way of reading and inspecting spatial data. By the end of this lesson, you should be able to:</p>
<ol type="1">
<li><p>Read in spatial data from both the vector and raster data model.</p></li>
<li><p>Recognize the required components of a spatial data object</p></li>
<li><p>Use <code>plot</code> as a way to perform a quick check on your data.</p></li>
</ol>
</section>
<section id="getting-started" class="level2">
<h2 class="anchored" data-anchor-id="getting-started">Getting Started</h2>
<p>First, <a href="https://classroom.github.com/a/XWzfBM16">join the repository</a>. Then, we’ll have to <a href="https://rstudio.aws.boisestate.edu/">get our credentials</a> and login to a <a href="https://rstudio.apps.aws.boisestate.edu/">new RStudio session</a>. Finally, create a new, version control, git-based project (using the link to the repo you just created).</p>
<p>Once you’ve done that, you’ll need to load your packages. We’re going to add 3 new packages to the <code>tidyverse</code>; the <code>sf</code>, <code>terra</code>, and <code>tidyterra</code> packages. We’ll also add the <code>googledrive</code> so that we can use a custom function for downloading data from a shared Google Drive folder. Note that when you load these, the conflicts that the <code>tidyverse</code> reports will be different. In order to overcome these conflicts, you’ll need to use explicit calls like <code>package::function</code> so <code>R</code> knows which ones to use.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(googledrive)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'sf' was built under R version 4.4.1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Linking to GEOS 3.11.0, GDAL 3.5.3, PROJ 9.1.0; sf_use_s2() is TRUE</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(terra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>terra 1.7.78</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyterra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'tidyterra'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:stats':

    filter</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.4.1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.2     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ tidyr::extract() masks terra::extract()
✖ dplyr::filter()  masks tidyterra::filter(), stats::filter()
✖ dplyr::lag()     masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
</div>
</section>
<section id="loading-a-custom-function" class="level2">
<h2 class="anchored" data-anchor-id="loading-a-custom-function">Loading a Custom Function</h2>
<p>You’ll notice that your <code>scripts/utilities</code> folder has a file called <code>download_utils.R</code>. This file has some custom functions for downloading data directly from websites and from a Google Drive Folder. In order to give yourself access to these functions you’ll need to <code>source</code> them into your environment. You can do this by typing:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"scripts/utilities/download_utils.R"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>The first time you run the <code>gdrive_folder_download</code> function, you’ll be taken to a webpage where you need to give <code>googledrive</code> access to your Google Drive folders. Make sure you’ve checked all the boxes and click Allow. You should get a message saying that authorization is complete and that you can close the tab.</p>
<p>Let’s run it now and download the data to our <code>original</code> folder. You’ll see that it requires two arguments, <code>filelst</code> and <code>dstfldr</code>. The first is a list of files in the folder, the second is the name of the destination folder. In order to generate the <code>filelst</code> we need to do some <code>googledrive</code> gymnastics to generate a data frame of the unique google drive id’s for each file. We then use <code>pmap</code> to download each file. You’ll notice that the destination path is printed to the screen.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>file_list <span class="ot">&lt;-</span> <span class="fu">drive_ls</span>(<span class="fu">drive_get</span>(<span class="fu">as_id</span>(<span class="st">"https://drive.google.com/drive/u/1/folders/1PwfUX2hnJlbnqBe3qvl33tFBImtNFTuR"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>! Using an auto-discovered, cached token.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>  To suppress this message, modify your code or options to clearly consent to
  the use of a cached token.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>  See gargle's "Non-interactive auth" vignette for more details:</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>  &lt;https://gargle.r-lib.org/articles/non-interactive-auth.html&gt;</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>ℹ The googledrive package is using a cached token for
  'mattwilliamson@boisestate.edu'.</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>file_list <span class="sc">%&gt;%</span> </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(id, name) <span class="sc">%&gt;%</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  purrr<span class="sc">::</span><span class="fu">pmap</span>(<span class="cf">function</span>(id, name) {</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">gdrive_folder_download</span>(<span class="fu">list</span>(<span class="at">id =</span> id, <span class="at">name =</span> name),</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>                           <span class="at">dstfldr =</span> <span class="st">"inclass07"</span>)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  })</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>File downloaded:</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• 'pa_censors_loc.csv' &lt;id: 13ZPu8E96ERWdUNlwQ5MB_vXrPCqvzxj_&gt;</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Saved locally as:</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• 'data/original/inclass07/pa.csv'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>File downloaded:</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• 'wildfire_hazard_agg.tif' &lt;id: 135PvMlKu17i7tZcrF7XiWxzrzaX-aCLn&gt;</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Saved locally as:</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• 'data/original/inclass07/wildfire.tif'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>File downloaded:</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• 'cejst_nw.shx' &lt;id: 1IXDayQ35MwCfq1UtuDHCtf5iNYq5VUqu&gt;</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Saved locally as:</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• 'data/original/inclass07/cejst.shx'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>File downloaded:</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• 'cejst_nw.dbf' &lt;id: 1PgCOsZsVEOhxQs2Dpz21MNz0kMb32amB&gt;</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Saved locally as:</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• 'data/original/inclass07/cejst.dbf'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>File downloaded:</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• 'cejst_nw.shp' &lt;id: 1ZeL_683mTTWdCDjQ4dY6oJsxyVZtQT6O&gt;</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Saved locally as:</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• 'data/original/inclass07/cejst.shp'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>File downloaded:</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• 'cejst_nw.prj' &lt;id: 1r7OHK1DHhoEMBToiM2FmuK5xmEzWSdrc&gt;</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Saved locally as:</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• 'data/original/inclass07/cejst.prj'</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
[1] "data/original/inclass07/pa.csv"

[[2]]
[1] "data/original/inclass07/wildfire.tif"

[[3]]
[1] "data/original/inclass07/cejst.shx"

[[4]]
[1] "data/original/inclass07/cejst.dbf"

[[5]]
[1] "data/original/inclass07/cejst.shp"

[[6]]
[1] "data/original/inclass07/cejst.prj"</code></pre>
</div>
</div>
</section>
<section id="reading-data-vectors" class="level2">
<h2 class="anchored" data-anchor-id="reading-data-vectors">Reading Data: Vectors</h2>
<p>The vector data (called <code>cejst</code>) comes from the Climate and Environmental Justice Screening Tool which is no longer available online. You’ll notice that there are multiple files with the same name, but different extensions. We’ll talk more about these different files in the next few weeks, but for now, just not that these files exist.</p>
<p>Because <code>sf</code> adheres to the <code>tidyverse</code> grammars, we can use a similar intuition to read in the data. You’ll note that even though we have all these extra files, we only need the <code>.shp</code> file. This is the shapefile which is the “overarching” file for all of the data.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>cejst_shp <span class="ot">&lt;-</span> <span class="fu">read_sf</span>(<span class="st">"data/original/inclass07/cejst.shp"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Now that you’ve got the data in, let’s take a look at it using <code>str</code> and <code>glimpse</code>.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(cejst_shp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>sf [2,590 × 124] (S3: sf/tbl_df/tbl/data.frame)
 $ GEOID10   : chr [1:2590] "16019970700" "16025970100" "16027021700" "16027020700" ...
 $ SF        : chr [1:2590] "Idaho" "Idaho" "Idaho" "Idaho" ...
 $ CF        : chr [1:2590] "Bonneville County" "Camas County" "Canyon County" "Canyon County" ...
 $ DF_PFS    : num [1:2590] 0.44 0.67 0.74 0.48 0.75 0.8 0.76 0.72 0.76 0.52 ...
 $ AF_PFS    : num [1:2590] 0.73 0.65 0.86 0.63 0.79 0.88 0.86 0.79 0.8 0.65 ...
 $ HDF_PFS   : num [1:2590] 0.57 0.79 0.69 0.47 0.72 0.55 0.53 0.71 0.74 0.45 ...
 $ DSF_PFS   : num [1:2590] 0.53 0 0.58 0.46 0.12 0.79 0.68 0.27 0.06 0.11 ...
 $ EBF_PFS   : num [1:2590] 0.63 0.95 0.54 0.3 0.63 0.81 0.81 0.44 0.73 0.52 ...
 $ EALR_PFS  : num [1:2590] 0.55 0.83 0.63 0.63 0.65 NA 0.41 0.64 0.65 0.64 ...
 $ EBLR_PFS  : num [1:2590] 0.19 0.93 0.05 0.55 0.09 0.09 0.08 0.09 0.47 0.17 ...
 $ EPLR_PFS  : num [1:2590] 0.8 0.99 0.09 0.1 0.11 0.31 0.08 0.09 0.1 0.09 ...
 $ HBF_PFS   : num [1:2590] 0.69 0.6 0.53 0.07 0.46 0.86 0.93 0.22 0.53 0.28 ...
 $ LLEF_PFS  : num [1:2590] 0.73 0.48 0.67 0.29 0.51 0.87 0.62 0.38 0.32 0.26 ...
 $ LIF_PFS   : num [1:2590] 0.54 0.54 0.53 0.12 0.48 0.61 0.88 0.46 0.41 0.32 ...
 $ LMI_PFS   : num [1:2590] 0.81 0.75 0.61 0.25 0.55 0.92 0.95 0.44 0.42 0.35 ...
 $ PM25F_PFS : num [1:2590] 0.11 0 0.68 0.63 0.42 0.66 0.69 0.57 0.26 0.4 ...
 $ HSEF      : num [1:2590] 0.14 0.06 0.2 0.08 0.21 0.24 0.31 0.18 0.18 0.09 ...
 $ P100_PFS  : num [1:2590] 0.83 0.63 0.47 0.24 0.6 0.72 0.93 0.27 0.39 0.33 ...
 $ P200_I_PFS: num [1:2590] 0.86 0.71 0.81 0.39 0.75 0.98 0.91 0.49 0.67 0.54 ...
 $ AJDLI_ET  : int [1:2590] 1 1 1 0 1 1 1 0 1 1 ...
 $ LPF_PFS   : num [1:2590] 0.75 0.52 0.26 0.3 0.65 0.62 0.63 0.4 0.51 0.36 ...
 $ KP_PFS    : num [1:2590] 0.86 0.21 0.84 0.21 0.61 0.57 0.21 0.43 0.9 0.21 ...
 $ NPL_PFS   : num [1:2590] 0.09 0.05 0.06 0.08 0.03 0.08 0.05 0.05 0.08 0.1 ...
 $ RMP_PFS   : num [1:2590] 0.49 0.01 0.56 0.84 0.26 0.96 0.58 0.36 0.1 0.2 ...
 $ TSDF_PFS  : num [1:2590] 0.22 0.01 0.14 0.42 0.07 0.55 0.13 0.11 0.1 0.19 ...
 $ TPF       : num [1:2590] 5589 1048 11701 3901 5059 ...
 $ TF_PFS    : num [1:2590] 0.55 0.06 0.54 0.53 0.28 0.71 0.83 0.24 0.05 0.09 ...
 $ UF_PFS    : num [1:2590] 0.61 0.16 0.64 0.33 0.66 0.86 0.8 0.45 0.47 0.61 ...
 $ WF_PFS    : num [1:2590] 0.03 0.11 0.98 0.24 0.79 0.98 0.98 0.85 0.42 0.04 ...
 $ UST_PFS   : num [1:2590] 0.59 0.02 0.44 0.31 0.17 0.73 0.83 0.13 0.06 0.18 ...
 $ N_WTR     : int [1:2590] 0 0 1 0 0 1 1 0 0 0 ...
 $ N_WKFC    : int [1:2590] 0 0 0 0 0 1 1 0 0 0 ...
 $ N_CLT     : int [1:2590] 0 1 0 0 0 1 1 0 0 0 ...
 $ N_ENY     : int [1:2590] 0 1 0 0 0 0 0 0 0 0 ...
 $ N_TRN     : int [1:2590] 0 0 0 0 0 0 0 0 1 0 ...
 $ N_HSG     : int [1:2590] 0 0 0 0 0 0 1 0 1 0 ...
 $ N_PLN     : int [1:2590] 0 0 0 0 0 1 0 0 0 0 ...
 $ N_HLTH    : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...
 $ SN_C      : int [1:2590] 0 1 1 0 0 1 1 0 1 0 ...
 $ SN_T      : chr [1:2590] NA NA NA NA ...
 $ DLI       : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...
 $ ALI       : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...
 $ PLHSE     : int [1:2590] 0 0 0 0 0 0 1 0 0 0 ...
 $ LMILHSE   : int [1:2590] 0 0 0 0 0 1 1 0 0 0 ...
 $ ULHSE     : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...
 $ EPL_ET    : int [1:2590] 0 1 0 0 0 0 0 0 0 0 ...
 $ EAL_ET    : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...
 $ EBL_ET    : int [1:2590] 0 1 0 0 0 0 0 0 0 0 ...
 $ EB_ET     : int [1:2590] 0 1 0 0 0 0 0 0 0 0 ...
 $ PM25_ET   : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...
 $ DS_ET     : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...
 $ TP_ET     : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...
 $ LPP_ET    : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...
 $ HRS_ET    : chr [1:2590] NA NA NA NA ...
 $ KP_ET     : int [1:2590] 0 0 0 0 0 0 0 0 1 0 ...
 $ HB_ET     : int [1:2590] 0 0 0 0 0 0 1 0 0 0 ...
 $ RMP_ET    : int [1:2590] 0 0 0 0 0 1 0 0 0 0 ...
 $ NPL_ET    : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...
 $ TSDF_ET   : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...
 $ WD_ET     : int [1:2590] 0 0 1 0 0 1 1 0 0 0 ...
 $ UST_ET    : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...
 $ DB_ET     : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...
 $ A_ET      : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...
 $ HD_ET     : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...
 $ LLE_ET    : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...
 $ UN_ET     : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...
 $ LISO_ET   : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...
 $ POV_ET    : int [1:2590] 0 0 0 0 0 0 1 0 0 0 ...
 $ LMI_ET    : int [1:2590] 0 0 0 0 0 1 1 0 0 0 ...
 $ IA_LMI_ET : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...
 $ IA_UN_ET  : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...
 $ IA_POV_ET : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...
 $ TC        : num [1:2590] 0 3 1 0 0 4 5 0 2 0 ...
 $ CC        : num [1:2590] 0 2 1 0 0 4 4 0 2 0 ...
 $ IAULHSE   : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...
 $ IAPLHSE   : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...
 $ IALMILHSE : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...
 $ IALMIL_76 : num [1:2590] NA NA NA NA NA NA NA NA NA NA ...
 $ IAPLHS_77 : num [1:2590] NA NA NA NA NA NA NA NA NA NA ...
 $ IAULHS_78 : num [1:2590] NA NA NA NA NA NA NA NA NA NA ...
 $ LHE       : int [1:2590] 1 0 1 0 1 1 1 1 1 0 ...
 $ IALHE     : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...
 $ IAHSEF    : num [1:2590] NA NA NA NA NA NA NA NA NA NA ...
 $ N_CLT_EOMI: int [1:2590] 0 1 0 0 0 1 1 0 0 0 ...
 $ N_ENY_EOMI: int [1:2590] 0 1 0 0 0 0 0 0 0 0 ...
 $ N_TRN_EOMI: int [1:2590] 0 0 0 0 0 0 0 1 1 0 ...
 $ N_HSG_EOMI: int [1:2590] 0 0 0 0 0 0 1 0 1 0 ...
 $ N_PLN_EOMI: int [1:2590] 0 0 0 0 0 1 0 0 0 0 ...
 $ N_WTR_EOMI: int [1:2590] 0 0 1 0 0 1 1 0 0 0 ...
 $ N_HLTH_88 : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...
 $ N_WKFC_89 : int [1:2590] 0 0 0 0 0 1 1 0 0 0 ...
 $ FPL200S   : int [1:2590] 1 1 1 0 1 1 1 0 1 0 ...
 $ N_WKFC_91 : int [1:2590] 1 0 1 0 1 1 1 1 1 0 ...
 $ TD_ET     : int [1:2590] 0 0 0 0 0 0 0 1 1 0 ...
 $ TD_PFS    : num [1:2590] 0.67 0.78 0.6 0.63 0.85 0.35 0.29 0.94 0.91 0.78 ...
 $ FLD_PFS   : num [1:2590] 0.83 0.88 0.43 0.24 0.82 0.93 0.97 0.44 0.49 0.71 ...
 $ WFR_PFS   : num [1:2590] 0.7 0.82 0.33 0.87 0.8 0.33 0.83 0.77 0.81 0.78 ...
 $ FLD_ET    : int [1:2590] 0 0 0 0 0 1 1 0 0 0 ...
 $ WFR_ET    : int [1:2590] 0 0 0 0 0 0 0 0 0 0 ...
  [list output truncated]
 - attr(*, "sf_column")= chr "geometry"
 - attr(*, "agr")= Factor w/ 3 levels "constant","aggregate",..: NA NA NA NA NA NA NA NA NA NA ...
  ..- attr(*, "names")= chr [1:123] "GEOID10" "SF" "CF" "DF_PFS" ...</code></pre>
</div>
</div>
<p>You’ll notice that this is a new data type:</p>
<p><code>sf [2,590 × 124] (S3: sf/tbl_df/tbl/data.frame)</code></p>
<p>You can read this to yourself as “cejst_shp” is an <code>sf</code> object with a <code>tbl_df</code> combined with. it. (It’s slightly more complicated than that, but this can give you an intuition).</p>
<p>Now let’s look at the output of glimpse:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(cejst_shp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 2,590
Columns: 124
$ GEOID10    &lt;chr&gt; "16019970700", "16025970100", "16027021700", "16027020700",…
$ SF         &lt;chr&gt; "Idaho", "Idaho", "Idaho", "Idaho", "Idaho", "Idaho", "Idah…
$ CF         &lt;chr&gt; "Bonneville County", "Camas County", "Canyon County", "Cany…
$ DF_PFS     &lt;dbl&gt; 0.44, 0.67, 0.74, 0.48, 0.75, 0.80, 0.76, 0.72, 0.76, 0.52,…
$ AF_PFS     &lt;dbl&gt; 0.73, 0.65, 0.86, 0.63, 0.79, 0.88, 0.86, 0.79, 0.80, 0.65,…
$ HDF_PFS    &lt;dbl&gt; 0.57, 0.79, 0.69, 0.47, 0.72, 0.55, 0.53, 0.71, 0.74, 0.45,…
$ DSF_PFS    &lt;dbl&gt; 0.53, 0.00, 0.58, 0.46, 0.12, 0.79, 0.68, 0.27, 0.06, 0.11,…
$ EBF_PFS    &lt;dbl&gt; 0.63, 0.95, 0.54, 0.30, 0.63, 0.81, 0.81, 0.44, 0.73, 0.52,…
$ EALR_PFS   &lt;dbl&gt; 0.55, 0.83, 0.63, 0.63, 0.65, NA, 0.41, 0.64, 0.65, 0.64, 0…
$ EBLR_PFS   &lt;dbl&gt; 0.19, 0.93, 0.05, 0.55, 0.09, 0.09, 0.08, 0.09, 0.47, 0.17,…
$ EPLR_PFS   &lt;dbl&gt; 0.80, 0.99, 0.09, 0.10, 0.11, 0.31, 0.08, 0.09, 0.10, 0.09,…
$ HBF_PFS    &lt;dbl&gt; 0.69, 0.60, 0.53, 0.07, 0.46, 0.86, 0.93, 0.22, 0.53, 0.28,…
$ LLEF_PFS   &lt;dbl&gt; 0.73, 0.48, 0.67, 0.29, 0.51, 0.87, 0.62, 0.38, 0.32, 0.26,…
$ LIF_PFS    &lt;dbl&gt; 0.54, 0.54, 0.53, 0.12, 0.48, 0.61, 0.88, 0.46, 0.41, 0.32,…
$ LMI_PFS    &lt;dbl&gt; 0.81, 0.75, 0.61, 0.25, 0.55, 0.92, 0.95, 0.44, 0.42, 0.35,…
$ PM25F_PFS  &lt;dbl&gt; 0.11, 0.00, 0.68, 0.63, 0.42, 0.66, 0.69, 0.57, 0.26, 0.40,…
$ HSEF       &lt;dbl&gt; 0.14, 0.06, 0.20, 0.08, 0.21, 0.24, 0.31, 0.18, 0.18, 0.09,…
$ P100_PFS   &lt;dbl&gt; 0.83, 0.63, 0.47, 0.24, 0.60, 0.72, 0.93, 0.27, 0.39, 0.33,…
$ P200_I_PFS &lt;dbl&gt; 0.86, 0.71, 0.81, 0.39, 0.75, 0.98, 0.91, 0.49, 0.67, 0.54,…
$ AJDLI_ET   &lt;int&gt; 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,…
$ LPF_PFS    &lt;dbl&gt; 0.75, 0.52, 0.26, 0.30, 0.65, 0.62, 0.63, 0.40, 0.51, 0.36,…
$ KP_PFS     &lt;dbl&gt; 0.86, 0.21, 0.84, 0.21, 0.61, 0.57, 0.21, 0.43, 0.90, 0.21,…
$ NPL_PFS    &lt;dbl&gt; 0.09, 0.05, 0.06, 0.08, 0.03, 0.08, 0.05, 0.05, 0.08, 0.10,…
$ RMP_PFS    &lt;dbl&gt; 0.49, 0.01, 0.56, 0.84, 0.26, 0.96, 0.58, 0.36, 0.10, 0.20,…
$ TSDF_PFS   &lt;dbl&gt; 0.22, 0.01, 0.14, 0.42, 0.07, 0.55, 0.13, 0.11, 0.10, 0.19,…
$ TPF        &lt;dbl&gt; 5589, 1048, 11701, 3901, 5059, 4681, 3006, 7423, 6653, 4693…
$ TF_PFS     &lt;dbl&gt; 0.55, 0.06, 0.54, 0.53, 0.28, 0.71, 0.83, 0.24, 0.05, 0.09,…
$ UF_PFS     &lt;dbl&gt; 0.61, 0.16, 0.64, 0.33, 0.66, 0.86, 0.80, 0.45, 0.47, 0.61,…
$ WF_PFS     &lt;dbl&gt; 0.03, 0.11, 0.98, 0.24, 0.79, 0.98, 0.98, 0.85, 0.42, 0.04,…
$ UST_PFS    &lt;dbl&gt; 0.59, 0.02, 0.44, 0.31, 0.17, 0.73, 0.83, 0.13, 0.06, 0.18,…
$ N_WTR      &lt;int&gt; 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ N_WKFC     &lt;int&gt; 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ N_CLT      &lt;int&gt; 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,…
$ N_ENY      &lt;int&gt; 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,…
$ N_TRN      &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,…
$ N_HSG      &lt;int&gt; 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,…
$ N_PLN      &lt;int&gt; 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ N_HLTH     &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ SN_C       &lt;int&gt; 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,…
$ SN_T       &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ DLI        &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ ALI        &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ PLHSE      &lt;int&gt; 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ LMILHSE    &lt;int&gt; 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ ULHSE      &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ EPL_ET     &lt;int&gt; 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ EAL_ET     &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,…
$ EBL_ET     &lt;int&gt; 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ EB_ET      &lt;int&gt; 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,…
$ PM25_ET    &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ DS_ET      &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ TP_ET      &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ LPP_ET     &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ HRS_ET     &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ KP_ET      &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,…
$ HB_ET      &lt;int&gt; 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ RMP_ET     &lt;int&gt; 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ NPL_ET     &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ TSDF_ET    &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ WD_ET      &lt;int&gt; 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ UST_ET     &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ DB_ET      &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ A_ET       &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ HD_ET      &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ LLE_ET     &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ UN_ET      &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ LISO_ET    &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ POV_ET     &lt;int&gt; 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ LMI_ET     &lt;int&gt; 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ IA_LMI_ET  &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ IA_UN_ET   &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ IA_POV_ET  &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ TC         &lt;dbl&gt; 0, 3, 1, 0, 0, 4, 5, 0, 2, 0, 0, 3, 0, 0, 0, 0, 1, 0, 0, 0,…
$ CC         &lt;dbl&gt; 0, 2, 1, 0, 0, 4, 4, 0, 2, 0, 0, 3, 0, 0, 0, 0, 1, 0, 0, 0,…
$ IAULHSE    &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ IAPLHSE    &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ IALMILHSE  &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ IALMIL_76  &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ IAPLHS_77  &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ IAULHS_78  &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ LHE        &lt;int&gt; 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,…
$ IALHE      &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ IAHSEF     &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ N_CLT_EOMI &lt;int&gt; 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,…
$ N_ENY_EOMI &lt;int&gt; 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,…
$ N_TRN_EOMI &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,…
$ N_HSG_EOMI &lt;int&gt; 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,…
$ N_PLN_EOMI &lt;int&gt; 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ N_WTR_EOMI &lt;int&gt; 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ N_HLTH_88  &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ N_WKFC_89  &lt;int&gt; 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ FPL200S    &lt;int&gt; 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,…
$ N_WKFC_91  &lt;int&gt; 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,…
$ TD_ET      &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,…
$ TD_PFS     &lt;dbl&gt; 0.67, 0.78, 0.60, 0.63, 0.85, 0.35, 0.29, 0.94, 0.91, 0.78,…
$ FLD_PFS    &lt;dbl&gt; 0.83, 0.88, 0.43, 0.24, 0.82, 0.93, 0.97, 0.44, 0.49, 0.71,…
$ WFR_PFS    &lt;dbl&gt; 0.70, 0.82, 0.33, 0.87, 0.80, 0.33, 0.83, 0.77, 0.81, 0.78,…
$ FLD_ET     &lt;int&gt; 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ WFR_ET     &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ ADJ_ET     &lt;int&gt; 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ IS_PFS     &lt;dbl&gt; 0.64, 0.16, 0.41, 0.53, 0.86, 0.46, 0.51, 0.70, 0.82, 0.86,…
$ IS_ET      &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,…
$ AML_ET     &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ FUDS_RAW   &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, "0", NA, NA, NA, NA, NA, NA…
$ FUDS_ET    &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ IMP_FLG    &lt;chr&gt; "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",…
$ DM_B       &lt;dbl&gt; 0.04, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.01,…
$ DM_AI      &lt;dbl&gt; 0.01, 0.00, 0.01, 0.00, 0.00, 0.02, 0.01, 0.00, 0.00, 0.00,…
$ DM_A       &lt;dbl&gt; 0.00, 0.00, 0.00, 0.01, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,…
$ DM_HI      &lt;dbl&gt; 0.00, 0.00, 0.01, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,…
$ DM_T       &lt;dbl&gt; 0.06, 0.00, 0.06, 0.04, 0.04, 0.06, 0.03, 0.01, 0.02, 0.00,…
$ DM_W       &lt;dbl&gt; 0.62, 0.98, 0.59, 0.88, 0.71, 0.54, 0.40, 0.81, 0.83, 0.85,…
$ DM_H       &lt;dbl&gt; 0.27, 0.01, 0.36, 0.07, 0.26, 0.42, 0.54, 0.16, 0.15, 0.11,…
$ DM_O       &lt;dbl&gt; 0.11, 0.00, 0.15, 0.02, 0.11, 0.12, 0.27, 0.03, 0.02, 0.02,…
$ AGE_10     &lt;dbl&gt; 0.18, 0.16, 0.15, 0.12, 0.12, 0.15, 0.17, 0.10, 0.10, 0.14,…
$ AGE_MIDDLE &lt;dbl&gt; 0.71, 0.65, 0.71, 0.71, 0.68, 0.77, 0.72, 0.71, 0.76, 0.66,…
$ AGE_OLD    &lt;dbl&gt; 0.10, 0.18, 0.13, 0.15, 0.18, 0.07, 0.09, 0.18, 0.12, 0.18,…
$ TA_COU_116 &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ TA_COUNT_C &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ TA_PERC    &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ TA_PERC_FE &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ UI_EXP     &lt;chr&gt; "Nation", "Nation", "Nation", "Nation", "Nation", "Nation",…
$ THRHLD     &lt;dbl&gt; 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21,…
$ geometry   &lt;MULTIPOLYGON [°]&gt; MULTIPOLYGON (((-112.0208 4..., MULTIPOLYGON (…</code></pre>
</div>
</div>
<p>The key addition here is the <code>geometry</code> column. This is where the magic of <code>tibbles</code> comes in - it’s a <code>list</code> column. These sorts of columns aren’t allowed in <code>data.frames</code> because they entail multiple (and potentially different) data types. They become critical for spatial data (and <code>sf</code> objects) as they contain the coordinates for where the object need to go!</p>
<p>In the previous examples, you got used to checking the various columns for (in-)feasible values. You should still do this; however, the introduction of the <code>geometry</code> column. <strong>Identifying problematic <code>geometry</code> is key component of ensuring your data is valid.</strong> Luckly, you can do this with:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">all</span>(<span class="fu">st_is_valid</span>(cejst_shp))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<p>Things look good for now! We’ll talk more about what to do when this returns <code>FALSE</code> in future classes.</p>
<p>One final check is to take a look at the data. We’ll learn more about how to make fancy maps in the future, but for now, there’s a quick check:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">st_geometry</span>(cejst_shp))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="07-lesson_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="reading-data-rasters" class="level2">
<h2 class="anchored" data-anchor-id="reading-data-rasters">Reading Data: Rasters</h2>
<p>Let’s switch gears a bit and run through same process with rasters. Unfortunately, the <code>terra</code> package uses a different syntax. I’ll do my best to highlight those difference as we go, but for now, let’s focus on the <code>terra</code> version of read.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>fire_prob <span class="ot">&lt;-</span> <span class="fu">rast</span>(<span class="st">"data/original/inclass07/wildfire.tif"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Importantly, <code>rast</code> does more than just read in data. You can look at <code>?rast</code> to learn some more of those functions.</p>
<p>Let’s look at the data with <code>str</code></p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(fire_prob)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>S4 class 'SpatRaster' [package "terra"]</code></pre>
</div>
</div>
<p>You’ll notice a much less verbose response that this is a <code>SpatRaster</code> data class. We’ll talk more about what this means in the next few weeks, but for now, just notice that this is a distinct class assigned to a very particular package.</p>
<p>What happens when you look at <code>glimpse</code></p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(fire_prob)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>#  A SpatRaster 4,016 x 4,607 x 1 layer (18,501,712 cells)
#  Resolution (x / y): (240 / 240)
#  Projected CRS: +proj=aea +lat_0=23 +lon_0=-96 +lat_1=29.5 +lat_2=45.5 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs
#  CRS projection units: meter &lt;m&gt;
#  Extent (x / y) : ([-2,294,745 / -1,189,065] , [ 2,208,735 /  3,172,575])

$ WHP_ID &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…</code></pre>
</div>
</div>
<p>You get a variety of additional information on the resolution, projection, and extent. What you don’t get, however, is a geometry or any info about where each cell should be. This is because for <code>raster</code> data, the geometry is <strong>implicit</strong> - if we know where the raster covers, and the cell size, then we know the rest of the information necessary to derie the geometry. The other thing you’ll notice is that there’s only 1 variable. This is again a function of the raster data type. Each layer can only contain information on one measurement and all of those measurements much be of the same data class. Rasters are essentially matrices where the rows are the x coordinates, the columns are the y coordinates, and the cell values are the measurement.</p>
<p>The last thing we might want to do is plot the raster to quickly make sure it looks like the thing we thought it would. The nice part about <code>terra</code> is that there is a basic <code>plot</code> function that you can use:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fire_prob)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="07-lesson_files/figure-html/plotrst-1.png" class="img-fluid" width="672"></p>
</div>
</div>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb60" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Data Models, Coordinates, and Geometries"</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a><span class="fu">## Objectives</span></span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>We're going to introduce the <span class="in">`sf`</span>, <span class="in">`terra`</span>, and <span class="in">`tidyterra`</span> packages today as a way of reading and inspecting spatial data. By the end of this lesson, you should be able to:</span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Read in spatial data from both the vector and raster data model.</span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Recognize the required components of a spatial data object</span>
<span id="cb60-12"><a href="#cb60-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-13"><a href="#cb60-13" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Use <span class="in">`plot`</span> as a way to perform a quick check on your data.</span>
<span id="cb60-14"><a href="#cb60-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-15"><a href="#cb60-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-16"><a href="#cb60-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-17"><a href="#cb60-17" aria-hidden="true" tabindex="-1"></a><span class="fu">## Getting Started</span></span>
<span id="cb60-18"><a href="#cb60-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-19"><a href="#cb60-19" aria-hidden="true" tabindex="-1"></a>First, <span class="co">[</span><span class="ot">join the repository</span><span class="co">](https://classroom.github.com/a/XWzfBM16)</span>. Then, we'll have to <span class="co">[</span><span class="ot">get our credentials</span><span class="co">](https://rstudio.aws.boisestate.edu/)</span> and login to a <span class="co">[</span><span class="ot">new RStudio session</span><span class="co">](https://rstudio.apps.aws.boisestate.edu/)</span>. Finally, create a new, version control, git-based project (using the link to the repo you just created). </span>
<span id="cb60-20"><a href="#cb60-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-21"><a href="#cb60-21" aria-hidden="true" tabindex="-1"></a>Once you've done that, you'll need to load your packages. We're going to add 3 new packages to the <span class="in">`tidyverse`</span>; the <span class="in">`sf`</span>, <span class="in">`terra`</span>, and <span class="in">`tidyterra`</span> packages. We'll also add the <span class="in">`googledrive`</span> so that we can use a custom function for downloading data from a shared Google Drive folder. Note that when you load these, the conflicts that the <span class="in">`tidyverse`</span> reports will be different. In order to overcome these conflicts, you'll need to use explicit calls like <span class="in">`package::function`</span> so <span class="in">`R`</span> knows which ones to use.</span>
<span id="cb60-22"><a href="#cb60-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-23"><a href="#cb60-23" aria-hidden="true" tabindex="-1"></a><span class="in">```{r ldpkg}</span></span>
<span id="cb60-24"><a href="#cb60-24" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(googledrive)</span>
<span id="cb60-25"><a href="#cb60-25" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb60-26"><a href="#cb60-26" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(terra)</span>
<span id="cb60-27"><a href="#cb60-27" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyterra)</span>
<span id="cb60-28"><a href="#cb60-28" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb60-29"><a href="#cb60-29" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb60-30"><a href="#cb60-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-31"><a href="#cb60-31" aria-hidden="true" tabindex="-1"></a><span class="fu">## Loading a Custom Function</span></span>
<span id="cb60-32"><a href="#cb60-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-33"><a href="#cb60-33" aria-hidden="true" tabindex="-1"></a>You'll notice that your <span class="in">`scripts/utilities`</span> folder has a file called <span class="in">`download_utils.R`</span>. This file has some custom functions for downloading data directly from websites and from a Google Drive Folder. In order to give yourself access to these functions you'll need to <span class="in">`source`</span> them into your environment. You can do this by typing:</span>
<span id="cb60-34"><a href="#cb60-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-35"><a href="#cb60-35" aria-hidden="true" tabindex="-1"></a><span class="in">```{r srcfun}</span></span>
<span id="cb60-36"><a href="#cb60-36" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"scripts/utilities/download_utils.R"</span>)</span>
<span id="cb60-37"><a href="#cb60-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-38"><a href="#cb60-38" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb60-39"><a href="#cb60-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-40"><a href="#cb60-40" aria-hidden="true" tabindex="-1"></a>The first time you run the <span class="in">`gdrive_folder_download`</span> function, you'll be taken to a webpage where you need to give <span class="in">`googledrive`</span> access to your Google Drive folders. Make sure you've checked all the boxes and click Allow. You should get a message saying that authorization is complete and that you can close the tab.</span>
<span id="cb60-41"><a href="#cb60-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-42"><a href="#cb60-42" aria-hidden="true" tabindex="-1"></a>Let's run it now and download the data to our <span class="in">`original`</span> folder. You'll see that it requires two arguments, <span class="in">`filelst`</span> and <span class="in">`dstfldr`</span>. The first is a list of files in the folder, the second is the name of the destination folder. In order to generate the <span class="in">`filelst`</span> we need to do some <span class="in">`googledrive`</span> gymnastics to generate a data frame of the unique google drive id's for each file. We then use <span class="in">`pmap`</span> to download each file. You'll notice that the destination path is printed to the screen.</span>
<span id="cb60-43"><a href="#cb60-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-44"><a href="#cb60-44" aria-hidden="true" tabindex="-1"></a><span class="in">```{r dldata}</span></span>
<span id="cb60-45"><a href="#cb60-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-46"><a href="#cb60-46" aria-hidden="true" tabindex="-1"></a>file_list <span class="ot">&lt;-</span> <span class="fu">drive_ls</span>(<span class="fu">drive_get</span>(<span class="fu">as_id</span>(<span class="st">"https://drive.google.com/drive/u/1/folders/1PwfUX2hnJlbnqBe3qvl33tFBImtNFTuR"</span>)))</span>
<span id="cb60-47"><a href="#cb60-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-48"><a href="#cb60-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-49"><a href="#cb60-49" aria-hidden="true" tabindex="-1"></a>file_list <span class="sc">%&gt;%</span> </span>
<span id="cb60-50"><a href="#cb60-50" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(id, name) <span class="sc">%&gt;%</span></span>
<span id="cb60-51"><a href="#cb60-51" aria-hidden="true" tabindex="-1"></a>  purrr<span class="sc">::</span><span class="fu">pmap</span>(<span class="cf">function</span>(id, name) {</span>
<span id="cb60-52"><a href="#cb60-52" aria-hidden="true" tabindex="-1"></a>    <span class="fu">gdrive_folder_download</span>(<span class="fu">list</span>(<span class="at">id =</span> id, <span class="at">name =</span> name),</span>
<span id="cb60-53"><a href="#cb60-53" aria-hidden="true" tabindex="-1"></a>                           <span class="at">dstfldr =</span> <span class="st">"inclass07"</span>)</span>
<span id="cb60-54"><a href="#cb60-54" aria-hidden="true" tabindex="-1"></a>  })</span>
<span id="cb60-55"><a href="#cb60-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-56"><a href="#cb60-56" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb60-57"><a href="#cb60-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-58"><a href="#cb60-58" aria-hidden="true" tabindex="-1"></a><span class="fu">## Reading Data: Vectors</span></span>
<span id="cb60-59"><a href="#cb60-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-60"><a href="#cb60-60" aria-hidden="true" tabindex="-1"></a>The vector data (called <span class="in">`cejst`</span>) comes from the Climate and Environmental Justice Screening Tool which is no longer available online. You'll notice that there are multiple files with the same name, but different extensions. We'll talk more about these different files in the next few weeks, but for now, just not that these files exist. </span>
<span id="cb60-61"><a href="#cb60-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-62"><a href="#cb60-62" aria-hidden="true" tabindex="-1"></a>Because <span class="in">`sf`</span> adheres to the <span class="in">`tidyverse`</span> grammars, we can use a similar intuition to read in the data. You'll note that even though we have all these extra files, we only need the <span class="in">`.shp`</span> file. This is the shapefile which is the "overarching" file for all of the data.</span>
<span id="cb60-63"><a href="#cb60-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-64"><a href="#cb60-64" aria-hidden="true" tabindex="-1"></a><span class="in">```{r readsf}</span></span>
<span id="cb60-65"><a href="#cb60-65" aria-hidden="true" tabindex="-1"></a>cejst_shp <span class="ot">&lt;-</span> <span class="fu">read_sf</span>(<span class="st">"data/original/inclass07/cejst.shp"</span>)</span>
<span id="cb60-66"><a href="#cb60-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-67"><a href="#cb60-67" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb60-68"><a href="#cb60-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-69"><a href="#cb60-69" aria-hidden="true" tabindex="-1"></a>Now that you've got the data in, let's take a look at it using <span class="in">`str`</span> and  <span class="in">`glimpse`</span>.</span>
<span id="cb60-70"><a href="#cb60-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-71"><a href="#cb60-71" aria-hidden="true" tabindex="-1"></a><span class="in">```{r looksf}</span></span>
<span id="cb60-72"><a href="#cb60-72" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(cejst_shp)</span>
<span id="cb60-73"><a href="#cb60-73" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb60-74"><a href="#cb60-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-75"><a href="#cb60-75" aria-hidden="true" tabindex="-1"></a>You'll notice that this is a new data type:</span>
<span id="cb60-76"><a href="#cb60-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-77"><a href="#cb60-77" aria-hidden="true" tabindex="-1"></a><span class="in">`sf [2,590 × 124] (S3: sf/tbl_df/tbl/data.frame)`</span></span>
<span id="cb60-78"><a href="#cb60-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-79"><a href="#cb60-79" aria-hidden="true" tabindex="-1"></a>You can read this to yourself as "cejst_shp" is an <span class="in">`sf`</span> object with a <span class="in">`tbl_df`</span> combined with. it. (It's slightly more complicated than that, but this can give you an intuition). </span>
<span id="cb60-80"><a href="#cb60-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-81"><a href="#cb60-81" aria-hidden="true" tabindex="-1"></a>Now let's look at the output of glimpse:</span>
<span id="cb60-82"><a href="#cb60-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-83"><a href="#cb60-83" aria-hidden="true" tabindex="-1"></a><span class="in">```{r glimpsf}</span></span>
<span id="cb60-84"><a href="#cb60-84" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(cejst_shp)</span>
<span id="cb60-85"><a href="#cb60-85" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb60-86"><a href="#cb60-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-87"><a href="#cb60-87" aria-hidden="true" tabindex="-1"></a>The key addition here is the <span class="in">`geometry`</span> column. This is where the magic of <span class="in">`tibbles`</span> comes in - it's a <span class="in">`list`</span> column. These sorts of columns aren't allowed in <span class="in">`data.frames`</span> because they entail multiple (and potentially different) data types. They become critical for spatial data (and <span class="in">`sf`</span> objects) as they contain the coordinates for where the object need to go!</span>
<span id="cb60-88"><a href="#cb60-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-89"><a href="#cb60-89" aria-hidden="true" tabindex="-1"></a>In the previous examples, you got used to checking the various columns for (in-)feasible values. You should still do this; however, the introduction of the <span class="in">`geometry`</span> column. **Identifying problematic `geometry` is key component of ensuring your data is valid.** Luckly, you can do this with:</span>
<span id="cb60-90"><a href="#cb60-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-91"><a href="#cb60-91" aria-hidden="true" tabindex="-1"></a><span class="in">```{r validity}</span></span>
<span id="cb60-92"><a href="#cb60-92" aria-hidden="true" tabindex="-1"></a><span class="fu">all</span>(<span class="fu">st_is_valid</span>(cejst_shp))</span>
<span id="cb60-93"><a href="#cb60-93" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb60-94"><a href="#cb60-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-95"><a href="#cb60-95" aria-hidden="true" tabindex="-1"></a>Things look good for now! We'll talk more about what to do when this returns <span class="in">`FALSE`</span> in future classes.</span>
<span id="cb60-96"><a href="#cb60-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-97"><a href="#cb60-97" aria-hidden="true" tabindex="-1"></a>One final check is to take a look at the data. We'll learn more about how to make fancy maps in the future, but for now, there's a quick check:</span>
<span id="cb60-98"><a href="#cb60-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-101"><a href="#cb60-101" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb60-102"><a href="#cb60-102" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">st_geometry</span>(cejst_shp))</span>
<span id="cb60-103"><a href="#cb60-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-104"><a href="#cb60-104" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb60-105"><a href="#cb60-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-106"><a href="#cb60-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-107"><a href="#cb60-107" aria-hidden="true" tabindex="-1"></a><span class="fu">## Reading Data: Rasters</span></span>
<span id="cb60-108"><a href="#cb60-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-109"><a href="#cb60-109" aria-hidden="true" tabindex="-1"></a>Let's switch gears a bit and run through same process with rasters. Unfortunately, the <span class="in">`terra`</span> package uses a different syntax. I'll do my best to highlight those difference as we go, but for now, let's focus on the <span class="in">`terra`</span> version of read.</span>
<span id="cb60-110"><a href="#cb60-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-111"><a href="#cb60-111" aria-hidden="true" tabindex="-1"></a><span class="in">```{r loadrst}</span></span>
<span id="cb60-112"><a href="#cb60-112" aria-hidden="true" tabindex="-1"></a>fire_prob <span class="ot">&lt;-</span> <span class="fu">rast</span>(<span class="st">"data/original/inclass07/wildfire.tif"</span>)</span>
<span id="cb60-113"><a href="#cb60-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-114"><a href="#cb60-114" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb60-115"><a href="#cb60-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-116"><a href="#cb60-116" aria-hidden="true" tabindex="-1"></a>Importantly, <span class="in">`rast`</span> does more than just read in data. You can look at <span class="in">`?rast`</span> to learn some more of those functions.</span>
<span id="cb60-117"><a href="#cb60-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-118"><a href="#cb60-118" aria-hidden="true" tabindex="-1"></a>Let's look at the data with <span class="in">`str`</span></span>
<span id="cb60-119"><a href="#cb60-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-120"><a href="#cb60-120" aria-hidden="true" tabindex="-1"></a><span class="in">```{r insprst}</span></span>
<span id="cb60-121"><a href="#cb60-121" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(fire_prob)</span>
<span id="cb60-122"><a href="#cb60-122" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb60-123"><a href="#cb60-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-124"><a href="#cb60-124" aria-hidden="true" tabindex="-1"></a>You'll notice a much less verbose response that this is a <span class="in">`SpatRaster`</span> data class. We'll talk more about what this means in the next few weeks, but for now, just notice that this is a distinct class assigned to a very particular package. </span>
<span id="cb60-125"><a href="#cb60-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-126"><a href="#cb60-126" aria-hidden="true" tabindex="-1"></a>What happens when you look at <span class="in">`glimpse`</span></span>
<span id="cb60-127"><a href="#cb60-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-128"><a href="#cb60-128" aria-hidden="true" tabindex="-1"></a><span class="in">```{r rstglimp}</span></span>
<span id="cb60-129"><a href="#cb60-129" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(fire_prob)</span>
<span id="cb60-130"><a href="#cb60-130" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb60-131"><a href="#cb60-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-132"><a href="#cb60-132" aria-hidden="true" tabindex="-1"></a>You get a variety of additional information on the resolution, projection, and extent. What you don't get, however, is a geometry or any info about where each cell should be. This is because for <span class="in">`raster`</span> data, the geometry is **implicit** - if we know where the raster covers, and the cell size, then we know the rest of the information necessary to derie the geometry. The other thing you'll notice is that there's only 1 variable. This is again a function of the raster data type. Each layer can only contain information on one measurement and all of those measurements much be of the same data class. Rasters are essentially matrices where the rows are the x coordinates, the columns are the y coordinates, and the cell values are the measurement.</span>
<span id="cb60-133"><a href="#cb60-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-134"><a href="#cb60-134" aria-hidden="true" tabindex="-1"></a>The last thing we might want to do is plot the raster to quickly make sure it looks like the thing we thought it would. The nice part about <span class="in">`terra`</span> is that there is a basic <span class="in">`plot`</span> function that you can use:</span>
<span id="cb60-135"><a href="#cb60-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-136"><a href="#cb60-136" aria-hidden="true" tabindex="-1"></a><span class="in">```{r plotrst}</span></span>
<span id="cb60-137"><a href="#cb60-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-138"><a href="#cb60-138" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fire_prob)</span>
<span id="cb60-139"><a href="#cb60-139" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Content <i class="fa-brands fa-creative-commons" aria-hidden="true"></i> 2025 by <a href="https://www.spaseslab.com">Matt Williamson</a> <br> All content licensed under a <i class="fa-brands fa-creative-commons" aria-hidden="true"></i> <i class="fa-brands fa-creative-commons-by" aria-hidden="true"></i> <i class="fa-brands fa-creative-commons-nc" aria-hidden="true"></i> <a href="https://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)</a></div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">Made with <i class="fa-brands fa-r-project" aria-hidden="true"></i> and <a href="https://quarto.org/">Quarto</a><br> <a href="https://www.github.com/mattwilliamson/isdrfall25">View the source at <i class="fa-brands fa-github" aria-hidden="true"></i> GitHub</a> Based on websites designed by <a href="https://github.com/andrewheiss/evalf22.classes.andrewheiss.com">Andrew Heiss</a></div>
  </div>
</footer>



</body></html>