<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Intro to Spatial Data in R - Interpolation and Kriging</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="..//files/iSDR_logo.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta property="og:title" content="Intro to Spatial Data in R - Interpolation and Kriging">
<meta property="og:description" content="">
<meta property="og:image" content="https://isdrfall25.classes.spaseslab.com/files/social-image-f22.png">
<meta property="og:site-name" content="Intro to Spatial Data in R">
<meta property="og:locale" content="en_US">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Intro to Spatial Data in R</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../syllabus.html" rel="" target="">
 <span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../schedule.html" rel="" target="">
 <span class="menu-text">Schedule</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../content/index.html" rel="" target="">
 <span class="menu-text">Content</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../assignment/index.html" rel="" target="">
 <span class="menu-text">Assignments</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../example/index.html" rel="" target="">
 <span class="menu-text">Examples</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../lesson/index.html" rel="" target="">
 <span class="menu-text">Lessons</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../resource/index.html" rel="" target="">
 <span class="menu-text">Resources</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://ecostatsbsu.slack.com/archives/CV4DEJ8M7" rel="" target=""><i class="bi bi-slack" role="img" aria-label="Slack">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/BSU-Spatial-Data-in-R-Fall2025" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://rstudio.apps.aws.boisestate.edu/" rel="" target=""><i class="bi bi-cloud-fill" role="img" aria-label="Rstudio">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#getting-started" id="toc-getting-started" class="nav-link active" data-scroll-target="#getting-started">Getting Started</a></li>
  <li><a href="#loading-the-data" id="toc-loading-the-data" class="nav-link" data-scroll-target="#loading-the-data">Loading the Data</a></li>
  <li><a href="#deterministic-approaches" id="toc-deterministic-approaches" class="nav-link" data-scroll-target="#deterministic-approaches">Deterministic Approaches</a>
  <ul class="collapse">
  <li><a href="#inverse-distance-weighting" id="toc-inverse-distance-weighting" class="nav-link" data-scroll-target="#inverse-distance-weighting">Inverse Distance Weighting</a></li>
  <li><a href="#thin-plate-splines" id="toc-thin-plate-splines" class="nav-link" data-scroll-target="#thin-plate-splines">Thin Plate Splines</a></li>
  <li><a href="#probabalistic-approaches-kriging" id="toc-probabalistic-approaches-kriging" class="nav-link" data-scroll-target="#probabalistic-approaches-kriging">Probabalistic approaches: Kriging</a></li>
  <li><a href="#variograms" id="toc-variograms" class="nav-link" data-scroll-target="#variograms">Variograms</a></li>
  <li><a href="#kriging" id="toc-kriging" class="nav-link" data-scroll-target="#kriging">Kriging</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Interpolation and Kriging</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="getting-started" class="level2">
<h2 class="anchored" data-anchor-id="getting-started">Getting Started</h2>
<p>We’ll be using the <code>meuse.all</code> data that ships with the <code>gstat</code> package as it is one that shows up in many explanations of geostatistical interpolation. It has the added bonus of being a reasonably small dataset to allow us to practice a few things without having to wait an extremly long time for the models to run. In addition to the <code>gstat</code> package, we’re adding the <code>fields</code> package which allows us to fit a variety of functional forms to spatial data. Beyond that, the rest of the packages should look familiar.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gstat)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Linking to GEOS 3.13.0, GDAL 3.8.5, PROJ 9.5.1; sf_use_s2() is TRUE</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(terra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>terra 1.8.70</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fields)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: spam</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Spam version 2.11-1 (2025-01-20) is loaded.
Type 'help( Spam)' or 'demo( spam)' for a short introduction 
and overview of this package.
Help for individual functions is also obtained by adding the
suffix '.spam' to the function name, e.g. 'help( chol.spam)'.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'spam'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    backsolve, forwardsolve</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: viridisLite</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: RColorBrewer</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Try help(fields) to get started.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'fields'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:terra':

    describe</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'patchwork'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:terra':

    area</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyterra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'tidyterra'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:stats':

    filter</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.1     ✔ stringr   1.5.2
✔ lubridate 1.9.4     ✔ tibble    3.3.0
✔ purrr     1.1.0     ✔ tidyr     1.3.1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ tidyr::extract() masks terra::extract()
✖ dplyr::filter()  masks tidyterra::filter(), stats::filter()
✖ dplyr::lag()     masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="loading-the-data" class="level2">
<h2 class="anchored" data-anchor-id="loading-the-data">Loading the Data</h2>
<p>Because the data ships with a package, we can use the <code>data</code> function to load it directly into our environment. Then we need to get it into an <code>sf</code> object. We’ll take a quick look at the CRS (with <code>st_crs</code>) just to get a sense for what the units look like.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(meuse.all)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>meuse_sf <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(meuse.all, </span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"x"</span>, <span class="st">"y"</span>), </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">crs =</span> <span class="dv">28992</span>, </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>                     <span class="at">agr =</span> <span class="st">"constant"</span>)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(meuse_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: EPSG:28992 
  wkt:
PROJCRS["Amersfoort / RD New",
    BASEGEOGCRS["Amersfoort",
        DATUM["Amersfoort",
            ELLIPSOID["Bessel 1841",6377397.155,299.1528128,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4289]],
    CONVERSION["RD New",
        METHOD["Oblique Stereographic",
            ID["EPSG",9809]],
        PARAMETER["Latitude of natural origin",52.1561605555556,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",5.38763888888889,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9999079,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",155000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",463000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["easting (X)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["northing (Y)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Engineering survey, topographic mapping."],
        AREA["Netherlands - onshore, including Waddenzee, Dutch Wadden Islands and 12-mile offshore coastal zone."],
        BBOX[50.75,3.2,53.7,7.22]],
    ID["EPSG",28992]]</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(meuse_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 164
Columns: 16
$ sample      &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,…
$ cadmium     &lt;dbl&gt; 11.7, 8.6, 6.5, 2.6, 2.8, 3.0, 3.2, 2.8, 2.4, 1.6, 1.4, 1.…
$ copper      &lt;dbl&gt; 85, 81, 68, 81, 48, 61, 31, 29, 37, 24, 25, 25, 93, 31, 27…
$ lead        &lt;dbl&gt; 299, 277, 199, 116, 117, 137, 132, 150, 133, 80, 86, 97, 2…
$ zinc        &lt;dbl&gt; 1022, 1141, 640, 257, 269, 281, 346, 406, 347, 183, 189, 2…
$ elev        &lt;dbl&gt; 7.909, 6.983, 7.800, 7.655, 7.480, 7.791, 8.217, 8.490, 8.…
$ dist.m      &lt;dbl&gt; 50, 30, 150, 270, 380, 470, 240, 120, 240, 420, 400, 300, …
$ om          &lt;dbl&gt; 13.6, 14.0, 13.0, 8.0, 8.7, 7.8, 9.2, 9.5, 10.6, 6.3, 6.4,…
$ ffreq       &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ soil        &lt;dbl&gt; 1, 1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ lime        &lt;dbl&gt; 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1…
$ landuse     &lt;fct&gt; Ah, Ah, Ah, Ga, Ah, Ga, Ah, Ab, Ab, W, Fh, Ag, W, Ah, Ah, …
$ in.pit      &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FA…
$ in.meuse155 &lt;lgl&gt; TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE…
$ in.BMcD     &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FA…
$ geometry    &lt;POINT [m]&gt; POINT (181072 333611), POINT (181025 333558), POINT …</code></pre>
</div>
</div>
<p>Now that you’ve gotten a chance to look at the data a bit, we’ll set up our interpolation grid. Unfortunately, the various interpolation functions available have different expectations for what data types your using to generate the interpolation model and grid so we’ve got to make a few different versions of these objects. To do this, I use <code>st_bbox</code> to get the bounding box for the data and convert that bbox into an <code>sf</code> object. Then, I create the interpolation grid by creating a blank raster within the bbox. We specify the resolution implicitly by specifying the number of rows and columns inside our raster. Once we have the raster, we convert into both a <code>data.frame</code> and an <code>sf</code> object. Lastly we bring a raster of the <code>meuse</code> dataset to provide a template fr cropping.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>box <span class="ot">&lt;-</span> <span class="fu">st_as_sfc</span>(<span class="fu">st_bbox</span>(meuse_sf))</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>grd <span class="ot">&lt;-</span> <span class="fu">rast</span>(<span class="fu">vect</span>(box), <span class="at">ncol=</span> <span class="dv">1000</span>, <span class="at">nrow=</span><span class="dv">1000</span>)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>grid_pts <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">crds</span>(grd, <span class="at">df =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="at">x =</span> x, <span class="at">y =</span> y)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>grid_sf <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(grid_pts, <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"x"</span>, <span class="st">"y"</span>), <span class="at">crs =</span> <span class="fu">st_crs</span>(meuse_sf))</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span><span class="fu">rast</span>(<span class="fu">system.file</span>(<span class="st">"ex/meuse.tif"</span>, <span class="at">package=</span><span class="st">"terra"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">project</span>(<span class="at">x=</span>_, <span class="at">y =</span> <span class="fu">crs</span>(<span class="st">"EPSG:28992"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">resample</span>(<span class="at">x=</span>_, <span class="at">y =</span> grd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="deterministic-approaches" class="level2">
<h2 class="anchored" data-anchor-id="deterministic-approaches">Deterministic Approaches</h2>
<section id="inverse-distance-weighting" class="level3">
<h3 class="anchored" data-anchor-id="inverse-distance-weighting">Inverse Distance Weighting</h3>
<p>The <code>gstat</code> function is similar to the <code>formula</code> function in base <code>R</code>, it’s just a way of taking the various arguments and constructing the appropriate spatial call. We pass an <code>id</code> parameter which <code>gstat</code> will use to identify the values produced by anything that uses the <code>formula</code> we construct. The <code>formula</code> argument allows us to specify what we want to model and how. In this case, we are using IDW so we are saying that zinc values are a function of (<code>~</code>) some unknown average. We pass a <code>locations</code> argument to let <code>gstat</code> know where the data and spatial locations are. The <code>nmax</code> argument sets the number of points that will be used to calculate our unknown average. Finally, the <code>set</code> argument accepts a variety of parameters that are specific to whichever form of model you are hoping to implement (you can find <a href="https://www.gstat.org/gstat.pdf">more information here at the original version of the <code>gstat</code> manual</a>).</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>idw_formula_lin <span class="ot">&lt;-</span> <span class="fu">gstat</span>(<span class="at">id =</span> <span class="st">"zinc"</span>, <span class="at">formula =</span> zinc<span class="sc">~</span><span class="dv">1</span>, <span class="at">locations =</span> meuse_sf, </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">nmax=</span><span class="dv">10</span>, <span class="at">set=</span><span class="fu">list</span>(<span class="at">idp =</span> <span class="dv">1</span>))</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>idw_formula_lin</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>data:
zinc : formula = zinc`~`1 ; data dim = 164 x 15 nmax = 10
set idp = 1; </code></pre>
</div>
</div>
<p>Once we have the formula set up, we can use the <code>predict</code> function to call the formula and predict values for all of the points in our grid. This outputs an <code>sf</code> object with predictions (and variance, though that is <code>NA</code> here because we’re using IDW) for all of the points. We convert that object to a raster with <code>rasterize</code> and mask it with our template raster (using <code>crop</code> with <code>mask=TRUE</code>) and combine our two rasters to plot them side by side.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>idw_interp <span class="ot">&lt;-</span> <span class="fu">predict</span>(idw_formula_lin, grid_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[inverse distance weighted interpolation]</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(idw_interp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Classes 'sf' and 'data.frame':  1000000 obs. of  3 variables:
 $ zinc.pred: num  993 993 993 993 993 ...
 $ zinc.var : num  NA NA NA NA NA NA NA NA NA NA ...
 $ geometry :sfc_POINT of length 1000000; first list element:  'XY' num  178606 333609
 - attr(*, "sf_column")= chr "geometry"
 - attr(*, "agr")= Factor w/ 3 levels "constant","aggregate",..: NA NA
  ..- attr(*, "names")= chr [1:2] "zinc.pred" "zinc.var"</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">rasterize</span>(idw_interp, grd, <span class="at">field =</span> <span class="st">"zinc.pred"</span>, <span class="at">fun =</span> <span class="st">"mean"</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>idw_lin_mask <span class="ot">&lt;-</span> <span class="fu">crop</span>(pred, r, <span class="at">mask=</span><span class="cn">TRUE</span>)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>comb_rst <span class="ot">&lt;-</span> <span class="fu">c</span>(pred, idw_lin_mask)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(comb_rst)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="19-lesson_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Now that we’ve got the basics of IDW syntax figured out, we might want to explore how changing the inverse-distance power (<code>idp</code>) affects the resulting predictions of our dataset. To do that, I build a custom function that accepts the necessary arguments for each of the above steps. I finish with a call to <code>ggplot</code> using <code>tidyterra</code> because I want to use <code>patchwork</code> to create a nice multipanel plot of the surfaces that result from the different <code>idp</code> values. I <code>map</code> through a series of values to create maps of different <code>idp</code> values.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>idw_idp_explore <span class="ot">&lt;-</span> <span class="cf">function</span>(variable, nmx, pwr, loc_sf, grid_sf, grid_rst, templ_rst){</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Need to convert the character variable name into something recognizeable as an object</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  dv <span class="ot">&lt;-</span> <span class="fu">sym</span>(variable)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Set up the idw formula to accept different arguments</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  idw_formula <span class="ot">&lt;-</span> <span class="fu">gstat</span>(<span class="at">id =</span> variable, <span class="at">formula =</span> <span class="fu">eval</span>(dv)<span class="sc">~</span><span class="dv">1</span>, <span class="at">locations =</span> loc_sf, </span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">nmax=</span>nmx, <span class="at">set=</span><span class="fu">list</span>(<span class="at">idp =</span> pwr))</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Generate spatial predictions as sf object</span></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>  pred_df <span class="ot">&lt;-</span> <span class="fu">predict</span>(idw_formula, grid_sf)</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Identify the column with the prediction</span></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>  fld <span class="ot">&lt;-</span> <span class="fu">str_subset</span>(<span class="fu">colnames</span>(pred_df),<span class="at">pattern =</span> <span class="st">"pred"</span>)</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Make and mask the raster</span></span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>  pred_rst <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">rasterize</span>(pred_df, grid_rst, <span class="at">field =</span> fld, <span class="at">fun =</span> <span class="st">"mean"</span>)</span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>  msk_rst <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">crop</span>(pred_rst, templ_rst, <span class="at">mask =</span> <span class="cn">TRUE</span>)</span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Make a plot</span></span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_spatraster</span>(<span class="at">data =</span> msk_rst, </span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a>                  <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">fill =</span> mean)) <span class="sc">+</span></span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>(<span class="at">na.value =</span> <span class="st">"transparent"</span>) <span class="sc">+</span></span>
<span id="cb37-19"><a href="#cb37-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="fu">paste0</span>(<span class="st">"Interp Zinc Concentration (IDW, power = "</span>, pwr, <span class="st">")"</span>)) <span class="sc">+</span></span>
<span id="cb37-20"><a href="#cb37-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb37-21"><a href="#cb37-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-22"><a href="#cb37-22" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb37-23"><a href="#cb37-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-24"><a href="#cb37-24" aria-hidden="true" tabindex="-1"></a>idp_plots <span class="ot">&lt;-</span> <span class="fu">map</span>(<span class="fu">c</span>(<span class="fl">0.5</span>, <span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">8</span>), </span>
<span id="cb37-25"><a href="#cb37-25" aria-hidden="true" tabindex="-1"></a>                 \(x) <span class="fu">idw_idp_explore</span>(<span class="at">variable =</span> <span class="st">"zinc"</span>, <span class="at">nmx =</span> <span class="dv">15</span>, </span>
<span id="cb37-26"><a href="#cb37-26" aria-hidden="true" tabindex="-1"></a>                                      <span class="at">pwr =</span> x, <span class="at">loc_sf =</span> meuse_sf, </span>
<span id="cb37-27"><a href="#cb37-27" aria-hidden="true" tabindex="-1"></a>                                      <span class="at">grid_sf =</span> grid_sf, <span class="at">grid_rst =</span> grd,</span>
<span id="cb37-28"><a href="#cb37-28" aria-hidden="true" tabindex="-1"></a>                                      <span class="at">templ_rst =</span> r))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[inverse distance weighted interpolation]</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>&lt;SpatRaster&gt; resampled to 501264 cells.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[inverse distance weighted interpolation]</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>&lt;SpatRaster&gt; resampled to 501264 cells.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[inverse distance weighted interpolation]</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>&lt;SpatRaster&gt; resampled to 501264 cells.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[inverse distance weighted interpolation]</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>&lt;SpatRaster&gt; resampled to 501264 cells.</code></pre>
</div>
</div>
<p>Then, I use patchwork to compose the resulting plots by accessing each of the plots in our <code>idp_plots</code> list.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>(idp_plots[[<span class="dv">1</span>]] <span class="sc">+</span> idp_plots[[<span class="dv">2</span>]])<span class="sc">/</span>(idp_plots[[<span class="dv">3</span>]] <span class="sc">+</span> idp_plots[[<span class="dv">4</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="19-lesson_files/figure-html/pltcmpidw-1.png" class="img-fluid" width="1248"></p>
</div>
</div>
</section>
<section id="thin-plate-splines" class="level3">
<h3 class="anchored" data-anchor-id="thin-plate-splines">Thin Plate Splines</h3>
<p>Thin plate splines (TPS) fit a smooth surface through scattered data in 2 (or more) dimensions by attempting to minimize the Residual Sum of Squares. The goal is to fit the data well while minimizing the total “bending energy” (i.e., surface roughness) of the surface. The <span class="math inline">\(\lambda\)</span> parameter controls the smoothness such that <span class="math inline">\(\lambda=0\)</span> produces an exact interpolation where the surface fits each data point exactly. Higher values of <span class="math inline">\(\lambda\)</span> increase the smoothness of the surface, but potentially provide a poor fit to the existing data.</p>
<p>The <code>fields</code> package implements TPS for spatial data and works direcly with <code>terra</code>. However, because of this, we have to convert our data into a format that will work with <code>terra</code>. In this case, that means converting our spatial coordinates to a matrix (using <code>st_coordinates</code>) and our variable of interest into a vector. Once we’ve done that, we can call <code>fields::Tps</code>.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>coords <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(meuse_sf)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> meuse_sf<span class="sc">$</span>zinc</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>tps_model_cv <span class="ot">&lt;-</span> fields<span class="sc">::</span><span class="fu">Tps</span>(coords, z)</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>tps_model_cv</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
fields::Tps(x = coords, Y = z)
                                                 
 Number of Observations:                164      
 Number of parameters in the null space 3        
 Parameters for fixed spatial drift     3        
 Model degrees of freedom:              68.8     
 Residual degrees of freedom:           95.2     
 GCV estimate for tau:                  186.8    
 MLE for tau:                           178.5    
 MLE for sigma:                         174700000
 lambda                                 0.00018  
 User supplied sigma                    NA       
 User supplied tau^2                    NA       
Summary of estimates: 
                 lambda      trA      GCV   tauHat -lnLike Prof converge
GCV        0.0001825072 68.84128 60141.03 186.8047     1137.245       10
GCV.model            NA       NA       NA       NA           NA       NA
GCV.one    0.0001825072 68.84128 60141.03 186.8047           NA       10
RMSE                 NA       NA       NA       NA           NA       NA
pure error           NA       NA       NA       NA           NA       NA
REML       0.0003770842 52.49955 60875.86 203.4412     1135.935        4</code></pre>
</div>
</div>
<p>By default, <code>fields::Tps</code> estimates <span class="math inline">\(\lambda\)</span> using a generalized cross-validation approach in order to balance the fit to the data with the degrees of freedom (number of knots) used by the spline. You can alter this approach by changing the <code>method</code> argument (see <code>?Tps</code> for the details). The nice part about using <code>fields::Tps</code> is that once the model has been fit, it can be used to make predictions very quickly even for large data. We do that using the <code>terra::interpolate</code> function and then mask our predictions again.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>tps_cv_rast <span class="ot">&lt;-</span> <span class="fu">interpolate</span>(grd, tps_model_cv)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>tps_cv_crop <span class="ot">&lt;-</span> <span class="fu">crop</span>(tps_cv_rast, r, <span class="at">mask=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>We’ll explore a couple of different <span class="math inline">\(\lambda\)</span> values and an alternative way of selecting <span class="math inline">\(\lambda\)</span> to demonstrate the effect of these different options on the resulting surface. We could write another function here, but I’m changing different things and passing different arguments so I’ll leave each call so that you can see what I’m changing.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>tps_model_03 <span class="ot">&lt;-</span> fields<span class="sc">::</span><span class="fu">Tps</span>(coords, z, <span class="at">lambda =</span> tps_model_cv<span class="sc">$</span>lambda<span class="sc">*</span><span class="dv">2</span>)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>tps_03_rast <span class="ot">&lt;-</span> <span class="fu">interpolate</span>(grd, tps_model_03)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>tps_03_crop <span class="ot">&lt;-</span> <span class="fu">crop</span>(tps_03_rast, r, <span class="at">mask=</span><span class="cn">TRUE</span>)</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>tps_model_00001 <span class="ot">&lt;-</span> fields<span class="sc">::</span><span class="fu">Tps</span>(coords, z, <span class="at">lambda =</span> tps_model_cv<span class="sc">$</span>lambda<span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>tps_00001_rast <span class="ot">&lt;-</span> <span class="fu">interpolate</span>(grd, tps_model_00001)</span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>tps_00001_crop <span class="ot">&lt;-</span> <span class="fu">crop</span>(tps_00001_rast, r, <span class="at">mask=</span><span class="cn">TRUE</span>)</span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>tps_model_cv_reml <span class="ot">&lt;-</span> fields<span class="sc">::</span><span class="fu">Tps</span>(coords, z, <span class="at">method =</span> <span class="st">"REML"</span>)</span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a>tps_cvreml_rast <span class="ot">&lt;-</span> <span class="fu">interpolate</span>(grd, tps_model_cv_reml)</span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a>tps_cvreml_crop <span class="ot">&lt;-</span> <span class="fu">crop</span>(tps_cvreml_rast, r, <span class="at">mask=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>tps_def <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_spatraster</span>(<span class="at">data =</span> tps_cv_crop, </span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">fill =</span> lyr<span class="fl">.1</span>)) <span class="sc">+</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>(<span class="at">na.value =</span> <span class="st">"transparent"</span>) <span class="sc">+</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Interp Zinc Concentration (TPS, lambda = default)"</span>) <span class="sc">+</span></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>&lt;SpatRaster&gt; resampled to 501264 cells.</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>tps_double <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_spatraster</span>(<span class="at">data =</span> tps_03_crop, </span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">fill =</span> lyr<span class="fl">.1</span>)) <span class="sc">+</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>(<span class="at">na.value =</span> <span class="st">"transparent"</span>) <span class="sc">+</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Interp Zinc Concentration (TPS, lambda = 0.0004)"</span>) <span class="sc">+</span></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>&lt;SpatRaster&gt; resampled to 501264 cells.</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>tps_half <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_spatraster</span>(<span class="at">data =</span> tps_00001_crop, </span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">fill =</span> lyr<span class="fl">.1</span>)) <span class="sc">+</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>(<span class="at">na.value =</span> <span class="st">"transparent"</span>) <span class="sc">+</span></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Interp Zinc Concentration (TPS, lambda = 0.000009)"</span>) <span class="sc">+</span></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>&lt;SpatRaster&gt; resampled to 501264 cells.</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>tps_reml <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_spatraster</span>(<span class="at">data =</span> tps_cvreml_crop, </span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">fill =</span> lyr<span class="fl">.1</span>)) <span class="sc">+</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>(<span class="at">na.value =</span> <span class="st">"transparent"</span>) <span class="sc">+</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Interp Zinc Concentration (TPS, lambda = REML)"</span>) <span class="sc">+</span></span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>&lt;SpatRaster&gt; resampled to 501264 cells.</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>(tps_def <span class="sc">+</span> tps_double)<span class="sc">/</span>(tps_half <span class="sc">+</span> tps_reml)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="19-lesson_files/figure-html/plttps-1.png" class="img-fluid" width="1248"></p>
</div>
</div>
<p>You can see that different values of at <span class="math inline">\(\lambda\)</span> smooth the surface differently (with the higher values allowing for more “bending” around the measured points giving higher values to the neighboring pixels than we’d get with lower <span class="math inline">\(\lambda\)</span> values). You can also see (in the bottom-right plot) that using a different method for automating the selection of <span class="math inline">\(\lambda\)</span> results in a different choice. While GCV is the default choice, it’s focus is to minimize the error values in a leave-one out cross-validation approach. The REML (Restricted Maximum Likelihood) approach tends to penalize overfitting of the data to find a parsimonious solution that explains most of the variation without adding unnecessary parameters. In practice, the REML approach tends to be more stable and is more likely to find the true minimum value for <span class="math inline">\(lambda\)</span>; however, it can be computationally costly and does not always converge on a solution.</p>
</section>
<section id="probabalistic-approaches-kriging" class="level3">
<h3 class="anchored" data-anchor-id="probabalistic-approaches-kriging">Probabalistic approaches: Kriging</h3>
<p>In the previous deterministic approaches, we’ve basically assumed that the function producing the measurements we have is stable throughout the landscape (i.e., homogeneous) and relied on that to assume that unmeasured locations should have values that are consistent with that rate and scaled by the distance between points (and potentially a smoothing parameter). These approaches are deterministic in that the measurements are fixed, the distances are known, and the smoothing parameter is set by you. They will generate the same prediction every time you run them so long as the smoothing parameter and the data you use remain the same.</p>
<p>We might imagine that we are uncertain whether the rate is homogeneous. Moreover, we might not be quite sure that the best prediction is simply a function of the distance between the points. In such cases, we might want to generate a probabilistic output (i.e., one with both predictions and variances.). <strong>Kriging</strong> allows us to do just that. It enables us to say that the mean value is unknown (and our measurements tell us something about what it should be), rather than assuming that the measurements are perfectly reflective of the underlying first-order process. It also allows us to use the empirical estimates of spatial covariance (i.e., how does variance among the points change as a function of distance) to estimate the role of distance in driving the process. We combine some “statistical machinery” to estimate these different elements and generate predictions along with the variance around those predictions. The key piece is to figure out the spatial covariance. We’ll do this using variograms.</p>
</section>
<section id="variograms" class="level3">
<h3 class="anchored" data-anchor-id="variograms">Variograms</h3>
<p>The <code>gstat</code> package has a <code>variogram</code> function that allows you to estimate the (semi-)variance between points as a function of distance. The semi-variance is just the “half” value of the variance because we are assuming that the function is <strong>isotropic</strong> (i.e., the same in both directions). We can look at the raw data first by setting the argument <code>cloud = TRUE</code>.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>zinc_vc <span class="ot">&lt;-</span> <span class="fu">variogram</span>(<span class="fu">log</span>(zinc) <span class="sc">~</span> <span class="dv">1</span>, meuse_sf, <span class="at">cloud =</span> <span class="cn">TRUE</span>)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(zinc_vc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="19-lesson_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Holy smokes!! That’s a lot of points!! We only have 164 measurements, so how do we get so many points? This calculation involves comparing the differences between all pairs of points. We can calculate this as: <span class="math display">\[
Pairs = \frac{N \times (N-1)}{2}
\]</span> Which in our case gives 13,366 points. These cloud plots can be helpful for identifying outliers or strange trends in the data, but are usually too overwhelming to identify things like the <strong>nugget, sill, and range</strong>. To look at the binned version of the plot (where the variances are combined into a series of lag-distance bins), we can just run the <code>variogram</code> function with its default argument of <code>cloud = FALSE</code>. In both cases, you can alter the number of points considered in the <code>variogram</code> by specifying a <code>cutoff</code> value which will eliminate pairs beyond a certain distance.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>sample_vgm <span class="ot">&lt;-</span> <span class="fu">variogram</span>(<span class="fu">log</span>(zinc) <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> meuse_sf)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sample_vgm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="19-lesson_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Inspection of this plot is much easier. We can see that the <strong>nugget</strong> (the semivariance when distances are small) is probably somewhere around 0.2, the <strong>partial sill</strong> (the point at which semivariance no longer seems to be a function of distance) occurs between 0.5 and 0.7, and the <strong>range</strong> (the distance at which the sill occurs) is probably around 1000m. Now we’ve got to figure out which of our variogram models makes sense to approximate this relationship.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">show.vgms</span>(<span class="at">par.strip.text =</span> <span class="fu">list</span>(<span class="at">cex =</span> <span class="fl">0.75</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="19-lesson_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This part is a bit more “art” than “science”, but that’s okay! The goal is to choose a functional form that does a reasonable job of approximating the relationship between distance and semivariance so that we can estimate the parameters necessary to input into our kriging model. Based on the shapes, we might choose a spherical (<code>Sph</code>) or Matern (<code>Mat</code>) shape. We can use the <code>vgm</code> function to generate the appropriate variograms based on our guesses above. These don’t have to be perfect, we will estimate the parameters in a subsequent step. For now, we are just trying to see if we like either of the shapes we’ve chosen once they are imposed on the data we actually have.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>sph_vgm_r900 <span class="ot">&lt;-</span> <span class="fu">vgm</span>(<span class="at">psill =</span> <span class="fl">0.5</span>, <span class="at">model =</span> <span class="st">"Sph"</span>,</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">range =</span> <span class="dv">900</span>, <span class="at">nugget =</span> <span class="fl">0.1</span>)</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sample_vgm, sph_vgm_r900, <span class="at">cutoff =</span> <span class="dv">1000</span>, <span class="at">cex =</span> <span class="fl">1.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="19-lesson_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>sph_vgm_Mat <span class="ot">&lt;-</span> <span class="fu">vgm</span>(<span class="at">psill =</span> <span class="fl">0.6</span>, <span class="at">model =</span> <span class="st">"Mat"</span>,</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">range =</span> <span class="dv">1100</span>, <span class="at">nugget =</span> <span class="fl">0.1</span>)</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sample_vgm, sph_vgm_Mat, <span class="at">cutoff =</span> <span class="dv">1000</span>, <span class="at">cex =</span> <span class="fl">1.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="19-lesson_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Based on these two plots, it doesn’t look like the Matern functional form generates enough “take off” in the values. That is, semivariance increases too slowly in the shorter distance lags. We’ll move forward with the spherical function and actually fit a model to estimate the parameters. When we use <code>fit.variogram</code> we provide the sample variogram as the <code>object</code> and then specify the model like we did in the previous step. We need to proivde the psill, nugget, and range as reasonable starting values to ensure that the empirical variogram can be estimated.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>fit_vgm <span class="ot">&lt;-</span> <span class="fu">fit.variogram</span>(<span class="at">object =</span> sample_vgm,</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">model =</span> <span class="fu">vgm</span>(<span class="at">psill =</span> <span class="fl">0.5</span>, <span class="at">model =</span> <span class="st">"Sph"</span>,</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>                                <span class="at">range =</span> <span class="dv">900</span>, <span class="at">nugget =</span> <span class="fl">0.1</span>))</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>fit_vgm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  model     psill    range
1   Nug 0.1229519   0.0000
2   Sph 0.5232435 880.9165</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sample_vgm, fit_vgm, <span class="at">cex =</span> <span class="fl">1.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="19-lesson_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The resuls show you what the estimate for the nugget (constant semivariance) model would be (0.12 which was pretty close to our guess) and then what the partial sill and range are under the spherical model (0.5 for the sill, and ~881 for the range). You can see that while our initial guesses were wrong, we didn’t do too badly!!</p>
</section>
<section id="kriging" class="level3">
<h3 class="anchored" data-anchor-id="kriging">Kriging</h3>
<p>Now that we’ve got our spatial covariance described and modelable, we can turn to generating predictions using kriging.</p>
<p><em>Ordinary Kriging</em></p>
<p>Ordinary kriging assumes that the (unknown) mean of the spatial process is constant and needs to be estimated. Once that estimate is obtained, we can adjust it based on the empirical variogram we built in the previous step. We use the <code>gstat</code> function to set up the necessary prediction formula, then the <code>predict</code> function to interpolate all of the values in our missing grid. Finally, we convert the data to a raster for plotting.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>ok_krig_formula <span class="ot">&lt;-</span> <span class="fu">gstat</span>(<span class="at">id =</span> <span class="st">"log.zinc"</span>,</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">formula =</span> <span class="fu">log</span>(zinc) <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> meuse_sf,</span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">model =</span> fit_vgm)</span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a>krig_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(ok_krig_formula, grid_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[using ordinary kriging]</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>pred_rast <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rasterize</span>(<span class="fu">vect</span>(krig_pred), grd, <span class="at">field=</span><span class="st">"log.zinc.pred"</span>), <span class="fu">rasterize</span>(<span class="fu">vect</span>(krig_pred), grd, <span class="at">field=</span><span class="st">"log.zinc.var"</span>))</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(pred_rast) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"pred"</span>, <span class="st">"var"</span>)</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>pred_rast_mask <span class="ot">&lt;-</span> <span class="fu">crop</span>(pred_rast, r, <span class="at">mask=</span><span class="cn">TRUE</span>)</span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pred_rast_mask)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="19-lesson_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>You can see from these plots that variance tends to be highest in places where our sample points are less dense and that the nature of the smoothing (more high values in the places where we have lots of high values and more low values in the places where our measurements were low) is different from those produced by deterministic models.</p>
<p><em>Universal kriging</em></p>
<p>Sometimes we might imagine that our unknown mean varies in space either as a function of location or of some other covariate. In those cases, we are estimating an <em>inhomogeneous process</em> as the first order mean can vary spatially. Universal kriging allows us to estimate the spatial trend in <span class="math inline">\(\mu\)</span> and then apply our spatial covariance to generate interpolations based on the process and our spatial covariance. Here, we use another preloaded dataset of soil types to add a predictor to describe what we think might be driving the inhomogeneity in the process. The only other difference is that we modify our formula in the <code>gstat</code> call to reflect that we think soil is driving the spatial process.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(meuse.grid, <span class="at">package =</span> <span class="st">"sp"</span>)</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>meuse_grid_sf <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(meuse.grid, <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"x"</span>, <span class="st">"y"</span>), <span class="at">crs =</span> <span class="dv">28992</span>)</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>univ_krig <span class="ot">&lt;-</span> <span class="fu">gstat</span>(<span class="at">id =</span> <span class="st">"log.zinc"</span>,</span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> <span class="fu">log</span>(zinc) <span class="sc">~</span> soil,      </span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">locations =</span> meuse_sf,              </span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">model =</span> fit_vgm</span>
<span id="cb71-9"><a href="#cb71-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb71-10"><a href="#cb71-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-11"><a href="#cb71-11" aria-hidden="true" tabindex="-1"></a>uk_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(univ_krig, meuse_grid_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[using universal kriging]</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(uk_pred) <span class="sc">+</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">color =</span> log.zinc.pred)) <span class="sc">+</span></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_c</span>() <span class="sc">+</span></span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Universal Kriging Prediction of Zinc"</span>,</span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Predicted Zn"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="19-lesson_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(uk_pred) <span class="sc">+</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">color =</span> log.zinc.var)) <span class="sc">+</span></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_c</span>() <span class="sc">+</span></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Universal Kriging Variance of Zinc"</span>,</span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Predicted Zn"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="19-lesson_files/figure-html/unnamed-chunk-13-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>You can see in this plot the “chunky” nature of the soil type data creates some new patterns in the prediction, but the variance patterns remain roughly the same.</p>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb75" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Interpolation and Kriging"</span></span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a><span class="fu">## Getting Started</span></span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a>We'll be using the <span class="in">`meuse.all`</span> data that ships with the <span class="in">`gstat`</span> package as it is one that shows up in many explanations of geostatistical interpolation. It has the added bonus of being a reasonably small dataset to allow us to practice a few things without having to wait an extremly long time for the models to run. In addition to the <span class="in">`gstat`</span> package, we're adding the <span class="in">`fields`</span> package which allows us to fit a variety of functional forms to spatial data. Beyond that, the rest of the packages should look familiar.</span>
<span id="cb75-8"><a href="#cb75-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-11"><a href="#cb75-11" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-12"><a href="#cb75-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gstat)</span>
<span id="cb75-13"><a href="#cb75-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb75-14"><a href="#cb75-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(terra)</span>
<span id="cb75-15"><a href="#cb75-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fields)</span>
<span id="cb75-16"><a href="#cb75-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb75-17"><a href="#cb75-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb75-18"><a href="#cb75-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyterra)</span>
<span id="cb75-19"><a href="#cb75-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb75-20"><a href="#cb75-20" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb75-21"><a href="#cb75-21" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-22"><a href="#cb75-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-23"><a href="#cb75-23" aria-hidden="true" tabindex="-1"></a><span class="fu">## Loading the Data</span></span>
<span id="cb75-24"><a href="#cb75-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-25"><a href="#cb75-25" aria-hidden="true" tabindex="-1"></a>Because the data ships with a package, we can use the <span class="in">`data`</span> function to load it directly into our environment. Then we need to get it into an <span class="in">`sf`</span> object. We'll take a quick look at the CRS (with <span class="in">`st_crs`</span>) just to get a sense for what the units look like.</span>
<span id="cb75-26"><a href="#cb75-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-27"><a href="#cb75-27" aria-hidden="true" tabindex="-1"></a><span class="in">```{r lddata}</span></span>
<span id="cb75-28"><a href="#cb75-28" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(meuse.all)</span>
<span id="cb75-29"><a href="#cb75-29" aria-hidden="true" tabindex="-1"></a>meuse_sf <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(meuse.all, </span>
<span id="cb75-30"><a href="#cb75-30" aria-hidden="true" tabindex="-1"></a>                     <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"x"</span>, <span class="st">"y"</span>), </span>
<span id="cb75-31"><a href="#cb75-31" aria-hidden="true" tabindex="-1"></a>                     <span class="at">crs =</span> <span class="dv">28992</span>, </span>
<span id="cb75-32"><a href="#cb75-32" aria-hidden="true" tabindex="-1"></a>                     <span class="at">agr =</span> <span class="st">"constant"</span>)</span>
<span id="cb75-33"><a href="#cb75-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-34"><a href="#cb75-34" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(meuse_sf)</span>
<span id="cb75-35"><a href="#cb75-35" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(meuse_sf)</span>
<span id="cb75-36"><a href="#cb75-36" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-37"><a href="#cb75-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-38"><a href="#cb75-38" aria-hidden="true" tabindex="-1"></a>Now that you've gotten a chance to look at the data a bit, we'll set up our interpolation grid. Unfortunately, the various interpolation functions available have different expectations for what data types your using to generate the interpolation model and grid so we've got to make a few different versions of these objects. To do this, I use <span class="in">`st_bbox`</span> to get the bounding box for the data and convert that bbox into an <span class="in">`sf`</span> object. Then, I create the interpolation grid by creating a blank raster within the bbox. We specify the resolution implicitly by specifying the number of rows and columns inside our raster. Once we have the raster, we convert into both a <span class="in">`data.frame`</span> and an <span class="in">`sf`</span> object. Lastly we bring a raster of the <span class="in">`meuse`</span> dataset to provide a template fr cropping.</span>
<span id="cb75-39"><a href="#cb75-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-42"><a href="#cb75-42" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-43"><a href="#cb75-43" aria-hidden="true" tabindex="-1"></a>box <span class="ot">&lt;-</span> <span class="fu">st_as_sfc</span>(<span class="fu">st_bbox</span>(meuse_sf))</span>
<span id="cb75-44"><a href="#cb75-44" aria-hidden="true" tabindex="-1"></a>grd <span class="ot">&lt;-</span> <span class="fu">rast</span>(<span class="fu">vect</span>(box), <span class="at">ncol=</span> <span class="dv">1000</span>, <span class="at">nrow=</span><span class="dv">1000</span>)</span>
<span id="cb75-45"><a href="#cb75-45" aria-hidden="true" tabindex="-1"></a>grid_pts <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">crds</span>(grd, <span class="at">df =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="at">x =</span> x, <span class="at">y =</span> y)</span>
<span id="cb75-46"><a href="#cb75-46" aria-hidden="true" tabindex="-1"></a>grid_sf <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(grid_pts, <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"x"</span>, <span class="st">"y"</span>), <span class="at">crs =</span> <span class="fu">st_crs</span>(meuse_sf))</span>
<span id="cb75-47"><a href="#cb75-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-48"><a href="#cb75-48" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span><span class="fu">rast</span>(<span class="fu">system.file</span>(<span class="st">"ex/meuse.tif"</span>, <span class="at">package=</span><span class="st">"terra"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb75-49"><a href="#cb75-49" aria-hidden="true" tabindex="-1"></a>  <span class="fu">project</span>(<span class="at">x=</span>_, <span class="at">y =</span> <span class="fu">crs</span>(<span class="st">"EPSG:28992"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb75-50"><a href="#cb75-50" aria-hidden="true" tabindex="-1"></a>  <span class="fu">resample</span>(<span class="at">x=</span>_, <span class="at">y =</span> grd)</span>
<span id="cb75-51"><a href="#cb75-51" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-52"><a href="#cb75-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-53"><a href="#cb75-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-54"><a href="#cb75-54" aria-hidden="true" tabindex="-1"></a><span class="fu">## Deterministic Approaches</span></span>
<span id="cb75-55"><a href="#cb75-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-56"><a href="#cb75-56" aria-hidden="true" tabindex="-1"></a><span class="fu">### Inverse Distance Weighting</span></span>
<span id="cb75-57"><a href="#cb75-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-58"><a href="#cb75-58" aria-hidden="true" tabindex="-1"></a>The <span class="in">`gstat`</span> function is similar to the <span class="in">`formula`</span> function in base <span class="in">`R`</span>, it's just a way of taking the various arguments and constructing the appropriate spatial call. We pass an <span class="in">`id`</span> parameter which <span class="in">`gstat`</span> will use to identify the values produced by anything that uses the <span class="in">`formula`</span> we construct. The <span class="in">`formula`</span> argument allows us to specify what we want to model and how. In this case, we are using IDW so we are saying that zinc values are a function of (<span class="in">`~`</span>) some unknown average. We pass a <span class="in">`locations`</span> argument to let <span class="in">`gstat`</span> know where the data and spatial locations are. The <span class="in">`nmax`</span> argument sets the number of points that will be used to calculate our unknown average. Finally, the <span class="in">`set`</span> argument accepts a variety of parameters that are specific to whichever form of model you are hoping to implement (you can find <span class="co">[</span><span class="ot">more information here at the original version of the `gstat` manual</span><span class="co">](https://www.gstat.org/gstat.pdf)</span>). </span>
<span id="cb75-59"><a href="#cb75-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-62"><a href="#cb75-62" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-63"><a href="#cb75-63" aria-hidden="true" tabindex="-1"></a>idw_formula_lin <span class="ot">&lt;-</span> <span class="fu">gstat</span>(<span class="at">id =</span> <span class="st">"zinc"</span>, <span class="at">formula =</span> zinc<span class="sc">~</span><span class="dv">1</span>, <span class="at">locations =</span> meuse_sf, </span>
<span id="cb75-64"><a href="#cb75-64" aria-hidden="true" tabindex="-1"></a>            <span class="at">nmax=</span><span class="dv">10</span>, <span class="at">set=</span><span class="fu">list</span>(<span class="at">idp =</span> <span class="dv">1</span>))</span>
<span id="cb75-65"><a href="#cb75-65" aria-hidden="true" tabindex="-1"></a>idw_formula_lin</span>
<span id="cb75-66"><a href="#cb75-66" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-67"><a href="#cb75-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-68"><a href="#cb75-68" aria-hidden="true" tabindex="-1"></a>Once we have the formula set up, we can use the <span class="in">`predict`</span> function to call the formula and predict values for all of the points in our grid. This outputs an <span class="in">`sf`</span> object with predictions (and variance, though that is <span class="in">`NA`</span> here because we're using IDW) for all of the points. We convert that object to a raster with <span class="in">`rasterize`</span> and mask it with our template raster (using <span class="in">`crop`</span> with <span class="in">`mask=TRUE`</span>) and combine our two rasters to plot them side by side.</span>
<span id="cb75-69"><a href="#cb75-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-72"><a href="#cb75-72" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-73"><a href="#cb75-73" aria-hidden="true" tabindex="-1"></a>idw_interp <span class="ot">&lt;-</span> <span class="fu">predict</span>(idw_formula_lin, grid_sf)</span>
<span id="cb75-74"><a href="#cb75-74" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(idw_interp)</span>
<span id="cb75-75"><a href="#cb75-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-76"><a href="#cb75-76" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">rasterize</span>(idw_interp, grd, <span class="at">field =</span> <span class="st">"zinc.pred"</span>, <span class="at">fun =</span> <span class="st">"mean"</span>)</span>
<span id="cb75-77"><a href="#cb75-77" aria-hidden="true" tabindex="-1"></a>idw_lin_mask <span class="ot">&lt;-</span> <span class="fu">crop</span>(pred, r, <span class="at">mask=</span><span class="cn">TRUE</span>)</span>
<span id="cb75-78"><a href="#cb75-78" aria-hidden="true" tabindex="-1"></a>comb_rst <span class="ot">&lt;-</span> <span class="fu">c</span>(pred, idw_lin_mask)</span>
<span id="cb75-79"><a href="#cb75-79" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(comb_rst)</span>
<span id="cb75-80"><a href="#cb75-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-81"><a href="#cb75-81" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-82"><a href="#cb75-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-83"><a href="#cb75-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-84"><a href="#cb75-84" aria-hidden="true" tabindex="-1"></a>Now that we've got the basics of IDW syntax figured out, we might want to explore how changing the inverse-distance power (<span class="in">`idp`</span>) affects the resulting predictions of our dataset. To do that, I build a custom function that accepts the necessary arguments for each of the above steps. I finish with a call to <span class="in">`ggplot`</span> using <span class="in">`tidyterra`</span> because I want to use <span class="in">`patchwork`</span> to create a nice multipanel plot of the surfaces that result from the different <span class="in">`idp`</span> values. I <span class="in">`map`</span> through a series of values to create maps of different <span class="in">`idp`</span> values.</span>
<span id="cb75-85"><a href="#cb75-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-88"><a href="#cb75-88" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-89"><a href="#cb75-89" aria-hidden="true" tabindex="-1"></a>idw_idp_explore <span class="ot">&lt;-</span> <span class="cf">function</span>(variable, nmx, pwr, loc_sf, grid_sf, grid_rst, templ_rst){</span>
<span id="cb75-90"><a href="#cb75-90" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Need to convert the character variable name into something recognizeable as an object</span></span>
<span id="cb75-91"><a href="#cb75-91" aria-hidden="true" tabindex="-1"></a>  dv <span class="ot">&lt;-</span> <span class="fu">sym</span>(variable)</span>
<span id="cb75-92"><a href="#cb75-92" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Set up the idw formula to accept different arguments</span></span>
<span id="cb75-93"><a href="#cb75-93" aria-hidden="true" tabindex="-1"></a>  idw_formula <span class="ot">&lt;-</span> <span class="fu">gstat</span>(<span class="at">id =</span> variable, <span class="at">formula =</span> <span class="fu">eval</span>(dv)<span class="sc">~</span><span class="dv">1</span>, <span class="at">locations =</span> loc_sf, </span>
<span id="cb75-94"><a href="#cb75-94" aria-hidden="true" tabindex="-1"></a>            <span class="at">nmax=</span>nmx, <span class="at">set=</span><span class="fu">list</span>(<span class="at">idp =</span> pwr))</span>
<span id="cb75-95"><a href="#cb75-95" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Generate spatial predictions as sf object</span></span>
<span id="cb75-96"><a href="#cb75-96" aria-hidden="true" tabindex="-1"></a>  pred_df <span class="ot">&lt;-</span> <span class="fu">predict</span>(idw_formula, grid_sf)</span>
<span id="cb75-97"><a href="#cb75-97" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Identify the column with the prediction</span></span>
<span id="cb75-98"><a href="#cb75-98" aria-hidden="true" tabindex="-1"></a>  fld <span class="ot">&lt;-</span> <span class="fu">str_subset</span>(<span class="fu">colnames</span>(pred_df),<span class="at">pattern =</span> <span class="st">"pred"</span>)</span>
<span id="cb75-99"><a href="#cb75-99" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Make and mask the raster</span></span>
<span id="cb75-100"><a href="#cb75-100" aria-hidden="true" tabindex="-1"></a>  pred_rst <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">rasterize</span>(pred_df, grid_rst, <span class="at">field =</span> fld, <span class="at">fun =</span> <span class="st">"mean"</span>)</span>
<span id="cb75-101"><a href="#cb75-101" aria-hidden="true" tabindex="-1"></a>  msk_rst <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">crop</span>(pred_rst, templ_rst, <span class="at">mask =</span> <span class="cn">TRUE</span>)</span>
<span id="cb75-102"><a href="#cb75-102" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Make a plot</span></span>
<span id="cb75-103"><a href="#cb75-103" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb75-104"><a href="#cb75-104" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_spatraster</span>(<span class="at">data =</span> msk_rst, </span>
<span id="cb75-105"><a href="#cb75-105" aria-hidden="true" tabindex="-1"></a>                  <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">fill =</span> mean)) <span class="sc">+</span></span>
<span id="cb75-106"><a href="#cb75-106" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>(<span class="at">na.value =</span> <span class="st">"transparent"</span>) <span class="sc">+</span></span>
<span id="cb75-107"><a href="#cb75-107" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="fu">paste0</span>(<span class="st">"Interp Zinc Concentration (IDW, power = "</span>, pwr, <span class="st">")"</span>)) <span class="sc">+</span></span>
<span id="cb75-108"><a href="#cb75-108" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb75-109"><a href="#cb75-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-110"><a href="#cb75-110" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb75-111"><a href="#cb75-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-112"><a href="#cb75-112" aria-hidden="true" tabindex="-1"></a>idp_plots <span class="ot">&lt;-</span> <span class="fu">map</span>(<span class="fu">c</span>(<span class="fl">0.5</span>, <span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">8</span>), </span>
<span id="cb75-113"><a href="#cb75-113" aria-hidden="true" tabindex="-1"></a>                 \(x) <span class="fu">idw_idp_explore</span>(<span class="at">variable =</span> <span class="st">"zinc"</span>, <span class="at">nmx =</span> <span class="dv">15</span>, </span>
<span id="cb75-114"><a href="#cb75-114" aria-hidden="true" tabindex="-1"></a>                                      <span class="at">pwr =</span> x, <span class="at">loc_sf =</span> meuse_sf, </span>
<span id="cb75-115"><a href="#cb75-115" aria-hidden="true" tabindex="-1"></a>                                      <span class="at">grid_sf =</span> grid_sf, <span class="at">grid_rst =</span> grd,</span>
<span id="cb75-116"><a href="#cb75-116" aria-hidden="true" tabindex="-1"></a>                                      <span class="at">templ_rst =</span> r))</span>
<span id="cb75-117"><a href="#cb75-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-118"><a href="#cb75-118" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-119"><a href="#cb75-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-120"><a href="#cb75-120" aria-hidden="true" tabindex="-1"></a>Then, I use patchwork to compose the resulting plots by accessing each of the plots in our <span class="in">`idp_plots`</span> list.</span>
<span id="cb75-121"><a href="#cb75-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-122"><a href="#cb75-122" aria-hidden="true" tabindex="-1"></a><span class="in">```{r pltcmpidw}</span></span>
<span id="cb75-123"><a href="#cb75-123" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 13</span></span>
<span id="cb75-124"><a href="#cb75-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-125"><a href="#cb75-125" aria-hidden="true" tabindex="-1"></a>(idp_plots[[<span class="dv">1</span>]] <span class="sc">+</span> idp_plots[[<span class="dv">2</span>]])<span class="sc">/</span>(idp_plots[[<span class="dv">3</span>]] <span class="sc">+</span> idp_plots[[<span class="dv">4</span>]])</span>
<span id="cb75-126"><a href="#cb75-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-127"><a href="#cb75-127" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-128"><a href="#cb75-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-129"><a href="#cb75-129" aria-hidden="true" tabindex="-1"></a><span class="fu">### Thin Plate Splines</span></span>
<span id="cb75-130"><a href="#cb75-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-131"><a href="#cb75-131" aria-hidden="true" tabindex="-1"></a>Thin plate splines (TPS) fit a smooth surface through scattered data in 2 (or more) dimensions by attempting to minimize the Residual Sum of Squares. The goal is to fit the data well while minimizing the total "bending energy" (i.e., surface roughness) of the surface. The $\lambda$ parameter controls the smoothness such that $\lambda=0$ produces an exact interpolation where the surface fits each data point exactly. Higher values of $\lambda$ increase the smoothness of the surface, but potentially provide a poor fit to the existing data.</span>
<span id="cb75-132"><a href="#cb75-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-133"><a href="#cb75-133" aria-hidden="true" tabindex="-1"></a>The <span class="in">`fields`</span> package implements TPS for spatial data and works direcly with <span class="in">`terra`</span>. However, because of this, we have to convert our data into a format that will work with <span class="in">`terra`</span>. In this case, that means converting our spatial coordinates to a matrix (using <span class="in">`st_coordinates`</span>) and our variable of interest into a vector. Once we've done that, we can call <span class="in">`fields::Tps`</span>. </span>
<span id="cb75-134"><a href="#cb75-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-135"><a href="#cb75-135" aria-hidden="true" tabindex="-1"></a><span class="in">```{r tpsex}</span></span>
<span id="cb75-136"><a href="#cb75-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-137"><a href="#cb75-137" aria-hidden="true" tabindex="-1"></a>coords <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(meuse_sf)</span>
<span id="cb75-138"><a href="#cb75-138" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> meuse_sf<span class="sc">$</span>zinc</span>
<span id="cb75-139"><a href="#cb75-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-140"><a href="#cb75-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-141"><a href="#cb75-141" aria-hidden="true" tabindex="-1"></a>tps_model_cv <span class="ot">&lt;-</span> fields<span class="sc">::</span><span class="fu">Tps</span>(coords, z)</span>
<span id="cb75-142"><a href="#cb75-142" aria-hidden="true" tabindex="-1"></a>tps_model_cv</span>
<span id="cb75-143"><a href="#cb75-143" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-144"><a href="#cb75-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-145"><a href="#cb75-145" aria-hidden="true" tabindex="-1"></a>By default, <span class="in">`fields::Tps`</span> estimates $\lambda$ using a generalized cross-validation approach in order to balance the fit to the data with the degrees of freedom (number of knots) used by the spline. You can alter this approach by changing the <span class="in">`method`</span> argument (see <span class="in">`?Tps`</span> for the details). The nice part about using <span class="in">`fields::Tps`</span> is that once the model has been fit, it can be used to make predictions very quickly even for large data. We do that using the <span class="in">`terra::interpolate`</span> function and then mask our predictions again.</span>
<span id="cb75-146"><a href="#cb75-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-147"><a href="#cb75-147" aria-hidden="true" tabindex="-1"></a><span class="in">```{r rsttps}</span></span>
<span id="cb75-148"><a href="#cb75-148" aria-hidden="true" tabindex="-1"></a>tps_cv_rast <span class="ot">&lt;-</span> <span class="fu">interpolate</span>(grd, tps_model_cv)</span>
<span id="cb75-149"><a href="#cb75-149" aria-hidden="true" tabindex="-1"></a>tps_cv_crop <span class="ot">&lt;-</span> <span class="fu">crop</span>(tps_cv_rast, r, <span class="at">mask=</span><span class="cn">TRUE</span>)</span>
<span id="cb75-150"><a href="#cb75-150" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-151"><a href="#cb75-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-152"><a href="#cb75-152" aria-hidden="true" tabindex="-1"></a>We'll explore a couple of different $\lambda$ values and an alternative way of selecting $\lambda$ to demonstrate the effect of these different options on the resulting surface. We could write another function here, but I'm changing different things and passing different arguments so I'll leave each call so that you can see what I'm changing.  </span>
<span id="cb75-153"><a href="#cb75-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-154"><a href="#cb75-154" aria-hidden="true" tabindex="-1"></a><span class="in">```{r tpsvary}</span></span>
<span id="cb75-155"><a href="#cb75-155" aria-hidden="true" tabindex="-1"></a>tps_model_03 <span class="ot">&lt;-</span> fields<span class="sc">::</span><span class="fu">Tps</span>(coords, z, <span class="at">lambda =</span> tps_model_cv<span class="sc">$</span>lambda<span class="sc">*</span><span class="dv">2</span>)</span>
<span id="cb75-156"><a href="#cb75-156" aria-hidden="true" tabindex="-1"></a>tps_03_rast <span class="ot">&lt;-</span> <span class="fu">interpolate</span>(grd, tps_model_03)</span>
<span id="cb75-157"><a href="#cb75-157" aria-hidden="true" tabindex="-1"></a>tps_03_crop <span class="ot">&lt;-</span> <span class="fu">crop</span>(tps_03_rast, r, <span class="at">mask=</span><span class="cn">TRUE</span>)</span>
<span id="cb75-158"><a href="#cb75-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-159"><a href="#cb75-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-160"><a href="#cb75-160" aria-hidden="true" tabindex="-1"></a>tps_model_00001 <span class="ot">&lt;-</span> fields<span class="sc">::</span><span class="fu">Tps</span>(coords, z, <span class="at">lambda =</span> tps_model_cv<span class="sc">$</span>lambda<span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb75-161"><a href="#cb75-161" aria-hidden="true" tabindex="-1"></a>tps_00001_rast <span class="ot">&lt;-</span> <span class="fu">interpolate</span>(grd, tps_model_00001)</span>
<span id="cb75-162"><a href="#cb75-162" aria-hidden="true" tabindex="-1"></a>tps_00001_crop <span class="ot">&lt;-</span> <span class="fu">crop</span>(tps_00001_rast, r, <span class="at">mask=</span><span class="cn">TRUE</span>)</span>
<span id="cb75-163"><a href="#cb75-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-164"><a href="#cb75-164" aria-hidden="true" tabindex="-1"></a>tps_model_cv_reml <span class="ot">&lt;-</span> fields<span class="sc">::</span><span class="fu">Tps</span>(coords, z, <span class="at">method =</span> <span class="st">"REML"</span>)</span>
<span id="cb75-165"><a href="#cb75-165" aria-hidden="true" tabindex="-1"></a>tps_cvreml_rast <span class="ot">&lt;-</span> <span class="fu">interpolate</span>(grd, tps_model_cv_reml)</span>
<span id="cb75-166"><a href="#cb75-166" aria-hidden="true" tabindex="-1"></a>tps_cvreml_crop <span class="ot">&lt;-</span> <span class="fu">crop</span>(tps_cvreml_rast, r, <span class="at">mask=</span><span class="cn">TRUE</span>)</span>
<span id="cb75-167"><a href="#cb75-167" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-168"><a href="#cb75-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-169"><a href="#cb75-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-170"><a href="#cb75-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-171"><a href="#cb75-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-172"><a href="#cb75-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-173"><a href="#cb75-173" aria-hidden="true" tabindex="-1"></a><span class="in">```{r plttps}</span></span>
<span id="cb75-174"><a href="#cb75-174" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 13</span></span>
<span id="cb75-175"><a href="#cb75-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-176"><a href="#cb75-176" aria-hidden="true" tabindex="-1"></a>tps_def <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb75-177"><a href="#cb75-177" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_spatraster</span>(<span class="at">data =</span> tps_cv_crop, </span>
<span id="cb75-178"><a href="#cb75-178" aria-hidden="true" tabindex="-1"></a>                  <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">fill =</span> lyr<span class="fl">.1</span>)) <span class="sc">+</span></span>
<span id="cb75-179"><a href="#cb75-179" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>(<span class="at">na.value =</span> <span class="st">"transparent"</span>) <span class="sc">+</span></span>
<span id="cb75-180"><a href="#cb75-180" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Interp Zinc Concentration (TPS, lambda = default)"</span>) <span class="sc">+</span></span>
<span id="cb75-181"><a href="#cb75-181" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb75-182"><a href="#cb75-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-183"><a href="#cb75-183" aria-hidden="true" tabindex="-1"></a>tps_double <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb75-184"><a href="#cb75-184" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_spatraster</span>(<span class="at">data =</span> tps_03_crop, </span>
<span id="cb75-185"><a href="#cb75-185" aria-hidden="true" tabindex="-1"></a>                  <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">fill =</span> lyr<span class="fl">.1</span>)) <span class="sc">+</span></span>
<span id="cb75-186"><a href="#cb75-186" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>(<span class="at">na.value =</span> <span class="st">"transparent"</span>) <span class="sc">+</span></span>
<span id="cb75-187"><a href="#cb75-187" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Interp Zinc Concentration (TPS, lambda = 0.0004)"</span>) <span class="sc">+</span></span>
<span id="cb75-188"><a href="#cb75-188" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb75-189"><a href="#cb75-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-190"><a href="#cb75-190" aria-hidden="true" tabindex="-1"></a>tps_half <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb75-191"><a href="#cb75-191" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_spatraster</span>(<span class="at">data =</span> tps_00001_crop, </span>
<span id="cb75-192"><a href="#cb75-192" aria-hidden="true" tabindex="-1"></a>                  <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">fill =</span> lyr<span class="fl">.1</span>)) <span class="sc">+</span></span>
<span id="cb75-193"><a href="#cb75-193" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>(<span class="at">na.value =</span> <span class="st">"transparent"</span>) <span class="sc">+</span></span>
<span id="cb75-194"><a href="#cb75-194" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Interp Zinc Concentration (TPS, lambda = 0.000009)"</span>) <span class="sc">+</span></span>
<span id="cb75-195"><a href="#cb75-195" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb75-196"><a href="#cb75-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-197"><a href="#cb75-197" aria-hidden="true" tabindex="-1"></a>tps_reml <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb75-198"><a href="#cb75-198" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_spatraster</span>(<span class="at">data =</span> tps_cvreml_crop, </span>
<span id="cb75-199"><a href="#cb75-199" aria-hidden="true" tabindex="-1"></a>                  <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">fill =</span> lyr<span class="fl">.1</span>)) <span class="sc">+</span></span>
<span id="cb75-200"><a href="#cb75-200" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>(<span class="at">na.value =</span> <span class="st">"transparent"</span>) <span class="sc">+</span></span>
<span id="cb75-201"><a href="#cb75-201" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Interp Zinc Concentration (TPS, lambda = REML)"</span>) <span class="sc">+</span></span>
<span id="cb75-202"><a href="#cb75-202" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb75-203"><a href="#cb75-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-204"><a href="#cb75-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-205"><a href="#cb75-205" aria-hidden="true" tabindex="-1"></a>(tps_def <span class="sc">+</span> tps_double)<span class="sc">/</span>(tps_half <span class="sc">+</span> tps_reml)</span>
<span id="cb75-206"><a href="#cb75-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-207"><a href="#cb75-207" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-208"><a href="#cb75-208" aria-hidden="true" tabindex="-1"></a>You can see that different values of at $\lambda$ smooth the surface differently (with the higher values allowing for more "bending" around the measured points giving higher values to the neighboring pixels than we'd get with lower $\lambda$ values). You can also see (in the bottom-right plot) that using a different method for automating the selection of $\lambda$ results in a different choice. While GCV is the default choice, it's focus is to minimize the error values in a leave-one out cross-validation approach. The REML (Restricted Maximum Likelihood) approach tends to penalize overfitting of the data to find a parsimonious solution that explains most of the variation without adding unnecessary parameters. In practice, the REML approach tends to be more stable and is more likely to find the true minimum value for $lambda$; however, it can be computationally costly and does not always converge on a solution.</span>
<span id="cb75-209"><a href="#cb75-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-210"><a href="#cb75-210" aria-hidden="true" tabindex="-1"></a><span class="fu">### Probabalistic approaches: Kriging</span></span>
<span id="cb75-211"><a href="#cb75-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-212"><a href="#cb75-212" aria-hidden="true" tabindex="-1"></a>In the previous deterministic approaches, we've basically assumed that the function producing the measurements we have is stable throughout the landscape (i.e., homogeneous) and relied on that to assume that unmeasured locations should have values that are consistent with that rate and scaled by the distance between points (and potentially a smoothing parameter). These approaches are deterministic in that the measurements are fixed, the distances are known, and the smoothing parameter is set by you. They will generate the same prediction every time you run them so long as the smoothing parameter and the data you use remain the same.</span>
<span id="cb75-213"><a href="#cb75-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-214"><a href="#cb75-214" aria-hidden="true" tabindex="-1"></a>We might imagine that we are uncertain whether the rate is homogeneous. Moreover, we might not be quite sure that the best prediction is simply a function of the distance between the points. In such cases, we might want to generate a probabilistic output (i.e., one with both predictions and variances.). **Kriging** allows us to do just that. It enables us to say that the mean value is unknown (and our measurements tell us something about what it should be), rather than assuming that the measurements are perfectly reflective of the underlying first-order process. It also allows us to use the empirical estimates of spatial covariance (i.e., how does variance among the points change as a function of distance) to estimate the role of distance in driving the process. We combine some "statistical machinery" to estimate these different elements and generate predictions along with the variance around those predictions. The key piece is to figure out the spatial covariance. We'll do this using variograms.</span>
<span id="cb75-215"><a href="#cb75-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-216"><a href="#cb75-216" aria-hidden="true" tabindex="-1"></a><span class="fu">### Variograms</span></span>
<span id="cb75-217"><a href="#cb75-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-218"><a href="#cb75-218" aria-hidden="true" tabindex="-1"></a>The <span class="in">`gstat`</span> package has a <span class="in">`variogram`</span> function that allows you to estimate the (semi-)variance between points as a function of distance. The semi-variance is just the "half" value of the variance because we are assuming that the function is **isotropic** (i.e., the same in both directions). We can look at the raw data first by setting the argument <span class="in">`cloud = TRUE`</span>.</span>
<span id="cb75-219"><a href="#cb75-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-222"><a href="#cb75-222" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-223"><a href="#cb75-223" aria-hidden="true" tabindex="-1"></a>zinc_vc <span class="ot">&lt;-</span> <span class="fu">variogram</span>(<span class="fu">log</span>(zinc) <span class="sc">~</span> <span class="dv">1</span>, meuse_sf, <span class="at">cloud =</span> <span class="cn">TRUE</span>)</span>
<span id="cb75-224"><a href="#cb75-224" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(zinc_vc)</span>
<span id="cb75-225"><a href="#cb75-225" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-226"><a href="#cb75-226" aria-hidden="true" tabindex="-1"></a>Holy smokes!! That's a lot of points!! We only have 164 measurements, so how do we get so many points? This calculation involves comparing the differences between all pairs of points. We can calculate this as:</span>
<span id="cb75-227"><a href="#cb75-227" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb75-228"><a href="#cb75-228" aria-hidden="true" tabindex="-1"></a>Pairs = \frac{N \times (N-1)}{2}</span>
<span id="cb75-229"><a href="#cb75-229" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb75-230"><a href="#cb75-230" aria-hidden="true" tabindex="-1"></a>Which in our case gives 13,366 points. These cloud plots can be helpful for identifying outliers or strange trends in the data, but are usually too overwhelming to identify things like the **nugget, sill, and range**. To look at the binned version of the plot (where the variances are combined into a series of lag-distance bins), we can just run the <span class="in">`variogram`</span> function with its default argument of <span class="in">`cloud = FALSE`</span>. In both cases, you can alter the number of points considered in the <span class="in">`variogram`</span> by specifying a <span class="in">`cutoff`</span> value which will eliminate pairs beyond a certain distance.</span>
<span id="cb75-231"><a href="#cb75-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-232"><a href="#cb75-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-235"><a href="#cb75-235" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-236"><a href="#cb75-236" aria-hidden="true" tabindex="-1"></a>sample_vgm <span class="ot">&lt;-</span> <span class="fu">variogram</span>(<span class="fu">log</span>(zinc) <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> meuse_sf)</span>
<span id="cb75-237"><a href="#cb75-237" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sample_vgm)</span>
<span id="cb75-238"><a href="#cb75-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-239"><a href="#cb75-239" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-240"><a href="#cb75-240" aria-hidden="true" tabindex="-1"></a>Inspection of this plot is much easier. We can see that the **nugget** (the semivariance when distances are small) is probably somewhere around 0.2, the **partial sill** (the point at which semivariance no longer seems to be a function of distance) occurs between 0.5 and 0.7, and the **range** (the distance at which the sill occurs) is probably around 1000m. Now we've got to figure out which of our variogram models makes sense to approximate this relationship.</span>
<span id="cb75-241"><a href="#cb75-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-244"><a href="#cb75-244" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-245"><a href="#cb75-245" aria-hidden="true" tabindex="-1"></a><span class="fu">show.vgms</span>(<span class="at">par.strip.text =</span> <span class="fu">list</span>(<span class="at">cex =</span> <span class="fl">0.75</span>))</span>
<span id="cb75-246"><a href="#cb75-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-247"><a href="#cb75-247" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-248"><a href="#cb75-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-249"><a href="#cb75-249" aria-hidden="true" tabindex="-1"></a>This part is a bit more "art" than "science", but that's okay! The goal is to choose a functional form that does a reasonable job of approximating the relationship between distance and semivariance so that we can estimate the parameters necessary to input into our kriging model. Based on the shapes, we might choose a spherical (<span class="in">`Sph`</span>) or Matern (<span class="in">`Mat`</span>) shape. We can use the <span class="in">`vgm`</span> function to generate the appropriate variograms based on our guesses above. These don't have to be perfect, we will estimate the parameters in a subsequent step. For now, we are just trying to see if we like either of the shapes we've chosen once they are imposed on the data we actually have. </span>
<span id="cb75-250"><a href="#cb75-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-253"><a href="#cb75-253" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-254"><a href="#cb75-254" aria-hidden="true" tabindex="-1"></a>sph_vgm_r900 <span class="ot">&lt;-</span> <span class="fu">vgm</span>(<span class="at">psill =</span> <span class="fl">0.5</span>, <span class="at">model =</span> <span class="st">"Sph"</span>,</span>
<span id="cb75-255"><a href="#cb75-255" aria-hidden="true" tabindex="-1"></a>                <span class="at">range =</span> <span class="dv">900</span>, <span class="at">nugget =</span> <span class="fl">0.1</span>)</span>
<span id="cb75-256"><a href="#cb75-256" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sample_vgm, sph_vgm_r900, <span class="at">cutoff =</span> <span class="dv">1000</span>, <span class="at">cex =</span> <span class="fl">1.5</span>)</span>
<span id="cb75-257"><a href="#cb75-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-258"><a href="#cb75-258" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-259"><a href="#cb75-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-260"><a href="#cb75-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-263"><a href="#cb75-263" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-264"><a href="#cb75-264" aria-hidden="true" tabindex="-1"></a>sph_vgm_Mat <span class="ot">&lt;-</span> <span class="fu">vgm</span>(<span class="at">psill =</span> <span class="fl">0.6</span>, <span class="at">model =</span> <span class="st">"Mat"</span>,</span>
<span id="cb75-265"><a href="#cb75-265" aria-hidden="true" tabindex="-1"></a>                <span class="at">range =</span> <span class="dv">1100</span>, <span class="at">nugget =</span> <span class="fl">0.1</span>)</span>
<span id="cb75-266"><a href="#cb75-266" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sample_vgm, sph_vgm_Mat, <span class="at">cutoff =</span> <span class="dv">1000</span>, <span class="at">cex =</span> <span class="fl">1.5</span>)</span>
<span id="cb75-267"><a href="#cb75-267" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-268"><a href="#cb75-268" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-269"><a href="#cb75-269" aria-hidden="true" tabindex="-1"></a>Based on these two plots, it doesn't look like the Matern functional form generates enough "take off" in the values. That is, semivariance increases too slowly in the shorter distance lags.  We'll move forward with the spherical function and actually fit a model to estimate the parameters. When we use <span class="in">`fit.variogram`</span> we provide the sample variogram as the <span class="in">`object`</span> and then specify the model like we did in the previous step. We need to proivde the psill, nugget, and range as reasonable starting values to ensure that the empirical variogram can be estimated.</span>
<span id="cb75-270"><a href="#cb75-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-273"><a href="#cb75-273" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-274"><a href="#cb75-274" aria-hidden="true" tabindex="-1"></a>fit_vgm <span class="ot">&lt;-</span> <span class="fu">fit.variogram</span>(<span class="at">object =</span> sample_vgm,</span>
<span id="cb75-275"><a href="#cb75-275" aria-hidden="true" tabindex="-1"></a>                    <span class="at">model =</span> <span class="fu">vgm</span>(<span class="at">psill =</span> <span class="fl">0.5</span>, <span class="at">model =</span> <span class="st">"Sph"</span>,</span>
<span id="cb75-276"><a href="#cb75-276" aria-hidden="true" tabindex="-1"></a>                                <span class="at">range =</span> <span class="dv">900</span>, <span class="at">nugget =</span> <span class="fl">0.1</span>))</span>
<span id="cb75-277"><a href="#cb75-277" aria-hidden="true" tabindex="-1"></a>fit_vgm</span>
<span id="cb75-278"><a href="#cb75-278" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sample_vgm, fit_vgm, <span class="at">cex =</span> <span class="fl">1.5</span>)</span>
<span id="cb75-279"><a href="#cb75-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-280"><a href="#cb75-280" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-281"><a href="#cb75-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-282"><a href="#cb75-282" aria-hidden="true" tabindex="-1"></a>The resuls show you what the estimate for the nugget (constant semivariance) model would be (0.12 which was pretty close to our guess) and then what the partial sill and range are under the spherical model (0.5 for the sill, and ~881 for the range). You can see that while our initial guesses were wrong, we didn't do too badly!!</span>
<span id="cb75-283"><a href="#cb75-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-284"><a href="#cb75-284" aria-hidden="true" tabindex="-1"></a><span class="fu">### Kriging</span></span>
<span id="cb75-285"><a href="#cb75-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-286"><a href="#cb75-286" aria-hidden="true" tabindex="-1"></a>Now that we've got our spatial covariance described and modelable, we can turn to generating predictions using kriging.</span>
<span id="cb75-287"><a href="#cb75-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-288"><a href="#cb75-288" aria-hidden="true" tabindex="-1"></a>_Ordinary Kriging_</span>
<span id="cb75-289"><a href="#cb75-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-290"><a href="#cb75-290" aria-hidden="true" tabindex="-1"></a>Ordinary kriging assumes that the (unknown) mean of the spatial process is constant and needs to be estimated. Once that estimate is obtained, we can adjust it based on the empirical variogram we built in the previous step. We use the <span class="in">`gstat`</span> function to set up the necessary prediction formula, then the <span class="in">`predict`</span> function to interpolate all of the values in our missing grid. Finally, we convert the data to a raster for plotting.</span>
<span id="cb75-291"><a href="#cb75-291" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-294"><a href="#cb75-294" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-295"><a href="#cb75-295" aria-hidden="true" tabindex="-1"></a>ok_krig_formula <span class="ot">&lt;-</span> <span class="fu">gstat</span>(<span class="at">id =</span> <span class="st">"log.zinc"</span>,</span>
<span id="cb75-296"><a href="#cb75-296" aria-hidden="true" tabindex="-1"></a>                      <span class="at">formula =</span> <span class="fu">log</span>(zinc) <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb75-297"><a href="#cb75-297" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> meuse_sf,</span>
<span id="cb75-298"><a href="#cb75-298" aria-hidden="true" tabindex="-1"></a>                      <span class="at">model =</span> fit_vgm)</span>
<span id="cb75-299"><a href="#cb75-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-300"><a href="#cb75-300" aria-hidden="true" tabindex="-1"></a>krig_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(ok_krig_formula, grid_sf)</span>
<span id="cb75-301"><a href="#cb75-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-302"><a href="#cb75-302" aria-hidden="true" tabindex="-1"></a>pred_rast <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rasterize</span>(<span class="fu">vect</span>(krig_pred), grd, <span class="at">field=</span><span class="st">"log.zinc.pred"</span>), <span class="fu">rasterize</span>(<span class="fu">vect</span>(krig_pred), grd, <span class="at">field=</span><span class="st">"log.zinc.var"</span>))</span>
<span id="cb75-303"><a href="#cb75-303" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(pred_rast) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"pred"</span>, <span class="st">"var"</span>)</span>
<span id="cb75-304"><a href="#cb75-304" aria-hidden="true" tabindex="-1"></a>pred_rast_mask <span class="ot">&lt;-</span> <span class="fu">crop</span>(pred_rast, r, <span class="at">mask=</span><span class="cn">TRUE</span>)</span>
<span id="cb75-305"><a href="#cb75-305" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pred_rast_mask)</span>
<span id="cb75-306"><a href="#cb75-306" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-307"><a href="#cb75-307" aria-hidden="true" tabindex="-1"></a>You can see from these plots that variance tends to be highest in places where our sample points are less dense and that the nature of the smoothing (more high values in the places where we have lots of high values and more low values in the places where our measurements were low) is different from those produced by deterministic models. </span>
<span id="cb75-308"><a href="#cb75-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-309"><a href="#cb75-309" aria-hidden="true" tabindex="-1"></a>_Universal kriging_</span>
<span id="cb75-310"><a href="#cb75-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-311"><a href="#cb75-311" aria-hidden="true" tabindex="-1"></a>Sometimes we might imagine that our unknown mean varies in space either as a function of location or of some other covariate. In those cases, we are estimating an _inhomogeneous process_ as the first order mean can vary spatially. Universal kriging allows us to estimate the spatial trend in $\mu$ and then apply our spatial covariance to generate interpolations based on the process and our spatial covariance. Here, we use another preloaded dataset of soil types to add a predictor to describe what we think might be driving the inhomogeneity in the process. The only other difference is that we modify our formula in the <span class="in">`gstat`</span> call to reflect that we think soil is driving the spatial process.</span>
<span id="cb75-312"><a href="#cb75-312" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-315"><a href="#cb75-315" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-316"><a href="#cb75-316" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(meuse.grid, <span class="at">package =</span> <span class="st">"sp"</span>)</span>
<span id="cb75-317"><a href="#cb75-317" aria-hidden="true" tabindex="-1"></a>meuse_grid_sf <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(meuse.grid, <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"x"</span>, <span class="st">"y"</span>), <span class="at">crs =</span> <span class="dv">28992</span>)</span>
<span id="cb75-318"><a href="#cb75-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-319"><a href="#cb75-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-320"><a href="#cb75-320" aria-hidden="true" tabindex="-1"></a>univ_krig <span class="ot">&lt;-</span> <span class="fu">gstat</span>(<span class="at">id =</span> <span class="st">"log.zinc"</span>,</span>
<span id="cb75-321"><a href="#cb75-321" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> <span class="fu">log</span>(zinc) <span class="sc">~</span> soil,      </span>
<span id="cb75-322"><a href="#cb75-322" aria-hidden="true" tabindex="-1"></a>  <span class="at">locations =</span> meuse_sf,              </span>
<span id="cb75-323"><a href="#cb75-323" aria-hidden="true" tabindex="-1"></a>  <span class="at">model =</span> fit_vgm</span>
<span id="cb75-324"><a href="#cb75-324" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb75-325"><a href="#cb75-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-326"><a href="#cb75-326" aria-hidden="true" tabindex="-1"></a>uk_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(univ_krig, meuse_grid_sf)</span>
<span id="cb75-327"><a href="#cb75-327" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-328"><a href="#cb75-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-329"><a href="#cb75-329" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(uk_pred) <span class="sc">+</span></span>
<span id="cb75-330"><a href="#cb75-330" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">color =</span> log.zinc.pred)) <span class="sc">+</span></span>
<span id="cb75-331"><a href="#cb75-331" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_c</span>() <span class="sc">+</span></span>
<span id="cb75-332"><a href="#cb75-332" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb75-333"><a href="#cb75-333" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Universal Kriging Prediction of Zinc"</span>,</span>
<span id="cb75-334"><a href="#cb75-334" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Predicted Zn"</span>)</span>
<span id="cb75-335"><a href="#cb75-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-336"><a href="#cb75-336" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(uk_pred) <span class="sc">+</span></span>
<span id="cb75-337"><a href="#cb75-337" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">color =</span> log.zinc.var)) <span class="sc">+</span></span>
<span id="cb75-338"><a href="#cb75-338" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_c</span>() <span class="sc">+</span></span>
<span id="cb75-339"><a href="#cb75-339" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb75-340"><a href="#cb75-340" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Universal Kriging Variance of Zinc"</span>,</span>
<span id="cb75-341"><a href="#cb75-341" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Predicted Zn"</span>)</span>
<span id="cb75-342"><a href="#cb75-342" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-343"><a href="#cb75-343" aria-hidden="true" tabindex="-1"></a>You can see in this plot the "chunky" nature of the soil type data creates some new patterns in the prediction, but the variance patterns remain roughly the same.</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Content <i class="fa-brands fa-creative-commons" aria-hidden="true"></i> 2025 by <a href="https://www.spaseslab.com">Matt Williamson</a> <br> All content licensed under a <i class="fa-brands fa-creative-commons" aria-hidden="true"></i> <i class="fa-brands fa-creative-commons-by" aria-hidden="true"></i> <i class="fa-brands fa-creative-commons-nc" aria-hidden="true"></i> <a href="https://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)</a></div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">Made with <i class="fa-brands fa-r-project" aria-hidden="true"></i> and <a href="https://quarto.org/">Quarto</a><br> <a href="https://www.github.com/mattwilliamson/isdrfall25">View the source at <i class="fa-brands fa-github" aria-hidden="true"></i> GitHub</a> Based on websites designed by <a href="https://github.com/andrewheiss/evalf22.classes.andrewheiss.com">Andrew Heiss</a></div>
  </div>
</footer>



</body></html>